### ISSUE TITLE
Javascript et langue - contenu clignotant

### ISSUE THREAD

**Issue by severo** [seenthis/seenthis_squelettes#101]
C'est rigolo, mon firefox est réglé avec ES-bo comme langue préférée, et en haut de chaque message ou commentaire, la date clignote entre les deux textes suivants:
- une seconde: "Fil hier"
- une seconde: "Fil ayer"

**Comment by severo** [comment]
synchro avec Fil: #102

**Comment by Fil** [comment]
ça alors! je ferme le mien inutile de doublonner :)

**Comment by archiloque** [comment]
On dirait un soucis dans le cache, je vois une ancienne version du fichier de date où la langue et le code étaient ensemble

**Comment by Fil** [comment]
j'ai vidé tous les caches : local/cache-js/ ; memcached ; varnish, et ça
continue... quel est le fichier qui est pas bon ?

-- Fil

2015-03-15 23:31 GMT+01:00 Julien Kirch <notifications@github.com>:

**Comment by archiloque** [comment]
calcul_date.js dont la partie traduction se trouve désormais dans js.calcul_date_lang.js

**Comment by Fil** [comment]
pourtant je suis up

svn up
plugins/plugins_seenthis/date_relative_dynamique/

à la révision 87989.


-- Fil

**Comment by Fil** [comment]
En fait dans le code je vois deux appels, donc deux process parallèles (et
qui parfois ne sont pas dans la même langue, ce qui fait que ça se voit) :

plugins/plugins_seenthis/date_relative_dynamique/calcul_date.php:
    $ret = "<script src='spip.php?page=js.calcul_date_lang&lang=$lang'
type='text/javascript'></script>";
    $ret .= "<script src='" . find_in_path("javascript/calcul_date.js") .
"' type='text/javascript'></script>";


plugins/seenthis_squelettes/javascript/seenthis/seenthis.js:
     $.getScript("index.php?page=js.calcul_date_lang&lang=" +
langue_visiteur)
plugins/seenthis_squelettes/js.textes_interface.html:
       $.getScript("index.php?page=js.calcul_date&lang=[(#GET{lalangue})]");


-- Fil

**Comment by Fil** [comment]
je crains qu'on ait maintenant un truc où la langue qui est envoyée n'est pas celle du visiteur : en effet avec un navigateur en anglais (no connecté), toute l'interface de seenthis m'apparaît en anglais, sauf les dates, qui sont réglées par l'inclusion dans le gros js compacté de `page=js.calcul_date_lang(lang=fr)`

**Comment by Fil** [comment]
ok j'ai dit une bêtise : mon test est fait sur un accès non connecté, donc j'ai `langue_visiteur = false` et la date m'arrive en valeur par défaut = fr, normal ; éventuellement on pourrait faire `langue_visiteur = (langue du navigateur)`, mais ça n'a rien à voir avec ce bug-ci
