### ISSUE TITLE
analyser le spam ?

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#110]
dans le répertoire tmp/ du site seenthis.net j'ai un fichier spam.log de 200Mo. Il contient l'ip et le texte de tous les spams reçus sur les formulaires seenthis. Est-qu'on peut éventuellement en faire quelque chose ? Sinon j'efface…

**Comment by archiloque** [comment]
une chaine de Markov ? :-)

**Comment by brunob** [comment]
Amha on peut fermer et supprimer ce fichier s'il existe encore.
