### ISSUE TITLE
Voir uniquement les seens d'une personne

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#119]
Il est possible d'utiliser Seenthis comme une plateforme de blog au lieu ou en plus de l'utiliser pour du partage. 

Sauf que… il n'existe aucune page pour voir uniquement les seens d'une personne. Du coup impossible d'avoir une URL à donner aux gens pour lire ce qu'écrit telle personne précise.

Dans les flux Atom il y a /only/feed.
Mais dans l'interface HTML il n'y a pas.

Il faudrait donc en HTML quelque chose comme /people/LOGIN/only  (et avec un lien bien visible sur cette page du genre "Voir uniquement les contenus de Machin").

**Comment by Fil** [comment]
fait avec 
https://github.com/seenthis/seenthis_squelettes/commit/c591029447b314ef2d0af69b04cd63398de0321f
et
https://github.com/seenthis/seenthis/commit/e360cb7ee51607f02af6748a59d07bb02c7a2695
