### ISSUE TITLE
ça saute quand on écrit en bas de la page

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#120]
http://seenthis.net/messages/356764#message357427
http://seenthis.net/messages/365819#message366539

**Comment by Fil** [comment]
d'après mes tests @archiloque c'est lié à la présence d'une url d'image dans le texte qu'on édite ; la div que tu crées pour ajouter les images devrait peut-être ne jamais pouvoir diminuer de hauteur ?  il suffit pour ça de faire un `jQuery(…) .css('min-height': $().height())` ?

**Comment by archiloque** [comment]
oui bonne idée de mettre un min-height

**Comment by Fil** [comment]
j'ai peut-être chopé le truc finalement : ajouté le min-height d'une part, et supprimé l'enchaînement de `.elastic()` qui créaient un listener de plus à chaque fois qu'on focusait sur le formulaire ; à rouvrir si le bug est encore présent…
