### ISSUE TITLE
Ajouter Internet Archive, Twitter, Scribd, d'autres ? à auto-embed

### ISSUE THREAD

**Issue by thibnton** [seenthis/seenthis_squelettes#122]
Ce serait chouette non ? (surtout pour Internet Archive j'avoue)

_Je me permets d'éditer ton message afin d'afficher la liste des sites sous forme de todo en tête de page ;)_

- [x] Internet Archive
- [ ] ~~Twitter~~ <= @martinarnaud semble contre
- [ ] Scribd
- [x] Jamendo
- [x] commons.wikimedia
- [ ] instagram

**Comment by archiloque** [comment]
Pas compris la demande :-/

**Comment by thibnton** [comment]
Faire en sorte que quand on ajoute un média, un film, un son ou un document depuis Internet Archive, un lecteur apparaisse sur Seenthis… Pareil pour quand on met le lien vers un tweet : que le tweet en question apparaisse, ou un lien vers un document scribd, que ledit document s'affiche. Ca fonctionne déjà avec les liens Youtube, Soundcloud ou Vimeo à l'heure actuelle. Suis-je plus clair ?!

**Comment by archiloque** [comment]
Oui c'est parfait, merci !

**Comment by JamesRezo** [comment]
Jamendo ? https://www.jamendo.com/fr/list/a106336/pirates-of-the-coast -> pourrait afficher leur widget ?

**Comment by thibnton** [comment]
Aussi ouais ! Tout ce qui est possible à vrai dire…

2015-05-12 10:28 GMT+02:00 James <notifications@github.com>:

**Comment by homlett** [comment]
Il y a une norme pour ça : http://www.oembed.com
Certains, comme Facebook, ne la respecte pas. Ça vaut peut-être le coup de regarder du côté de Noembed alors : https://noembed.com

**Comment by homlett** [comment]
J'ajoute que l'embed de vidéos Dailymotion exige Flash. Or la version actuelle, basée sur une iframe, supporte flash et l'HTML5.
La doc oEmbed : https://developer.dailymotion.com/documentation#player-oembed

**Comment by brunob** [comment]
Il faudrait peut-être envisager d'utiliser le plugin oembed pour ça non ?

http://plugins.spip.net/oembed.html

**Comment by martinarnaud** [comment]
Pas dingue dingue. Je sais que c’est très à la mode, mais ça a deux gros défauts:

- les Tweets ça parasite totalement le flux, parce que graphiquement c’est ultra-marqué,

- les Tweets ont généralement un contenu qui n’est pas pertinent dans le flux Seenthis (parce qu’il faut que ça tienne en 140 caractères). Un copier-coller-nettoyer me semble généralement plus adapté.

- pour les autres, si je comprends, c’est du contenu long, et pour le coup ça n’a rien à faire dans le flux Seenthis. C’est une des raisons pour lesquelles j’avais écarté le plugin Oembed pour développer le mien: ça passait son temps à récupérer tout plein de contenu textuel (genre WordPress, Wikipédia…), et ça ne colle pas avec l’idée d’un site de référencement commenté. 

Mais bon, si vous avez des exemples d’usages spécifiques, je suis intéressé à ce qu’on regarde ça, hein.

Arnaud

**Comment by brunob** [comment]
Hop,

>  les Tweets ça parasite totalement le flux, parce que graphiquement c’est ultra-marqué,

J'ai pas l'impression que ça soit si "marqué", cf l'exemple en ligne ici : http://labo.eliaz.fr/article80.html

![tw](https://cloud.githubusercontent.com/assets/418064/14580600/a7157ab0-03d2-11e6-8ee0-9961ac4e9d35.png)

Mais bon, perso je m'en cogne des twits, mais je remarque que pas mal de gens en postent sur seenthis.

> Pour les autres...

Le premier de la liste de souhaits me semble intéressant, Archive, car de plus en plus de monde y dépose du son par exemple. Pour le reste, je n'ai pas d'avis.

**Comment by Fil** [comment]
commons.wikimedia ici
https://seenthis.net/messages/224091

**Comment by brunob** [comment]
Voici un patch qui permet de prendre en charger les fichiers ogg et mp3 de commons.wikimedia : 

```php
Index: autoembed.php
===================================================================
--- autoembed.php	(révision 102521)
+++ autoembed.php	(copie de travail)
@@ -19,7 +19,13 @@
 
 	// Gérer les elements de dropbox (remplacer www par dl)
 	$url = preg_replace("/^(https\:\/\/)(www)(\.dropbox\.com\/.*\/.*\/.*?)(\?dl=[01])?$/", '\1dl\3', $url);
-
+	
+	// Gérer les elements de commons.wikimedia
+	if (preg_match("/^https?\:\/\/commons\.wikimedia\.org\/wiki\/File\:(.*)/i", $url, $regs)) {
+		$md5 = md5($regs[1]);
+		$url = 'https://upload.wikimedia.org/wikipedia/commons/' . $md5[0] . '/' . $md5[0] . $md5[1] . '/' . urlencode($regs[1]);
+	}
+	
 	// Si l'embed a deja été sauvegardé
 	if (file_exists(_DIR_CACHE."$host/$dossier/$fichier")) {
 		$html = implode("", file(_DIR_CACHE."$host/$dossier/$fichier"));
```

Source de l'astuce pour le coup du md5 : https://commons.wikimedia.org/wiki/Commons:FAQ#What_are_the_strangely_named_components_in_file_paths.3F

Reste à gérer les images, mais j'ai l'impression qu'on fait ça plutôt dans seenthis et non autoembed...

https://github.com/seenthis/seenthis/blob/master/inc/traiter_texte.php#L107

Sinon, je peux tenter me brancher sur l'API mediawiki ou utiliser l'astuce du Special:Redirect/file cf https://commons.wikimedia.org/wiki/Special:Redirect/file

**Comment by brunob** [comment]
Je vois qu'on a du code en double, par exemple la gestion des liens dropbox est présente dans autoembed et dans seenthis, donc voici le patch à envoyer dans seenthis pour la prise en charge des images de commons : 

```diff
diff --git a/inc/traiter_texte.php b/inc/traiter_texte.php
index 0683091..1a67087 100644
--- a/inc/traiter_texte.php
+++ b/inc/traiter_texte.php
@@ -111,6 +111,12 @@ function _creer_lien_riche($lien) {
 		// Gérer les images en lien dropbox (remplacer www par dl)
 		$lien = preg_replace("/^(https\:\/\/)(www)(\.dropbox\.com\/.*\/.*\/.*)$/", '\1dl\3', $lien);
 
+		// Gérer les images de commons.wikimedia
+		if (preg_match("/^https?\:\/\/commons\.wikimedia\.org\/wiki\/File\:(.*)/i", $lien, $regs)) {
+			$md5 = md5($regs[1]);
+			$lien = 'https://upload.wikimedia.org/wikipedia/commons/' . $md5[0] . '/' . $md5[0] . $md5[1] . '/' . urlencode($regs[1]);
+		}
+
 		// liens vers des ressources github (ajouter ?raw=true)
 		if (preg_match(",^https://(github\.com/[^/]+/[^/]+)/blob/(.*)$,",
 		$lien)) {
```

**Comment by brunob** [comment]
Intégré dans seenthis et autoembed cf https://zone.spip.org/trac/spip-zone/changeset/102555

**Comment by brunob** [comment]
@JamesRezo et voilà pour jamendo (même si leur player est vilain) : https://zone.spip.org/trac/spip-zone/changeset/102558

**Comment by brunob** [comment]
Et hop pour archive.org, dont j'ai testé l'audio et la video cf https://zone.spip.org/trac/spip-zone/changeset/102562 (pas encore le top mais ça fait le job, cf mon log de commit).

**Comment by brunob** [comment]
Je crois qu'il va falloir affiner pour achive.org, car ça attrape bien top de liens cf : 

https://seenthis.net/sites/112320

Ça fonctionne bien dans certains cas comme ici : https://seenthis.net/messages/532531#message534052

Mais ça foire sur les urls en `stream` comme ici : https://seenthis.net/messages/529210#message529375

À voir si c'est améliorable ou s'il faut lâcher l'affaire...

**Comment by Fil** [comment]
j'ai ajouté instagram dans la todo cf https://seenthis.net/messages/642695#message642774

**Comment by rastapopougros** [comment]
Mais le plugin oEmbed maintenu par la communauté permet de définir ce qui est en liste blanche ou pas, non ? Donc ce n'est pas obligé d'insérer les tweets, ou autre service qu'on ne veut pas sur seenthis, suivant comment on le paramètre.

Du coup je ne vois pas l'intérêt de maintenir un plugin séparé qui fait moins de chose au lieu de profiter du truc commun.

**Comment by brunob** [comment]
On se retrouve @rastapopougros c'est exactement ce que je proposais dans un commentaire précédent, mais la proposition ne semble pas avoir eu succès. À noter que autoembed, comme indiqué dans le fichier INSTALL, n'est pas de l'oembed cf : 

https://zone.spip.org/trac/spip-zone/browser/_plugins_/plugins_seenthis/autoembed/INSTALL#L8

Par exemple, le plugin prend en charge les mp3 et les ogg sans passer par oembed.

**Comment by brunob** [comment]
Je m'occupe d'ajouter la prise en charge instagram dès que j'ai un moment, et je fermerai le ticket quand ça sera fait (même si scribd n'est pas encore intégré).

Ainsi ça évitera de garder un ticket à rallonge ouvert depuis des mois dans le tracker, amha on devrait créer un ticket pour chaque ajout, sans quoi c'est compliqué pour les personnes qui assurent la maintnenance de s'y retrouver :)

**Comment by brunob** [comment]
Et voilà pour instagram : https://zone.spip.org/trac/spip-zone/changeset/107409
