### ISSUE TITLE
le repérage de liens en doublons ne devrait pas envoyer vers des réponses

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#126]
http://seenthis.net/messages/378243

**Comment by brunob** [comment]
Il doit suffire de modifier `action_messages_lien` afin qu'elle renvoie l'id_me du parent s'il y en a un et zou, non ? Ça permettrait de fixer le bug dans détection utilisée lors de la rédaction du message, ce qui me semble suffisant.

**Comment by brunob** [comment]
Après réflexion, le problème me semble être qu'on peut accéder à une page qui affiche un message "hors de son fil". C'est peut-être ça qu'il faut corriger avant tout ? Par exemple en modifiant le squelette qui affiche un message afin qu'il rediriger sur le message qui lance le fil.

**Comment by rastapopougros** [comment]
Ça peut être par une redirection après coup dans le squelette oui, mais ça pourrait aussi être dans la fonction de génération de l'URL de l'objet non ? enfin ya un comportement par défaut magique, mais on peut le préciser pour tel ou tel objet, donc là le préciser pour celui là, et quand on détecte que tel message est un commentaire, ne pas générer /messages/456 mais /messages/123#456

**Comment by brunob** [comment]
Voilà, la redirection depuis le squelette d'un message est proposée dans le commit cité ci-dessus.

@rastapopougros 
> Ça peut être par une redirection après coup dans le squelette oui, mais ça pourrait aussi être dans la fonction de génération de l'URL de l'objet non ?

Oui, c'est bien ce que fait le code la balise `#URL_ME` cf https://github.com/seenthis/seenthis/blob/master/urls/seenthis.php#L61 mais l'action `action_messages_lien` n'utilise pas ces fonctions et génère l'url des message en mode roulé sous les aisselles cf https://github.com/seenthis/seenthis_squelettes/blob/master/action/messages_lien.php#L19 => c'est là qu'il faut corriger je pense, patch à venir pour relecture.

**Comment by brunob** [comment]
Et voilà, la PR attend vos +1 ou -1 :)
