### ISSUE TITLE
les destinataires d'un message long flottent et c'est pas beau

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#129]
signalé par Cristina

![capture d ecran 2015-08-08 a 10 46 34](https://cloud.githubusercontent.com/assets/7001/9149813/49eb2e0c-3dbc-11e5-8669-70ed6d41021c.jpg)

cc @BoOz

**Comment by brunob** [comment]
Je ne reproduis pas à ce jour, cf https://seenthis.net/messages/396524

On ferme ?

**Comment by brunob** [comment]
Bug plus présent, pas de retour, on ferme :)
