### ISSUE TITLE
Identifier les articles des commentaires dans les notifications mail

### ISSUE THREAD

**Issue by pick-a-chu** [seenthis/seenthis_squelettes#132]
Il n'est pas facile de distinguer les nouveaux articles des commentaires a première vue, sans avoir à ouvrir le mail. Est-ce qu'il serait possible de distinguer les deux cas ? En mettant par exemple un "+" devant le début du message pour signifier que c'est un article ?

**Comment by Fil** [comment]
Classiquement les réponses sont préfixées par `Re: `, ce serait peut-être mieux ?

**Comment by pick-a-chu** [comment]
Oui sans doute

**Comment by Fil** [comment]
tu veux faire la pull-request ?

**Comment by pick-a-chu** [comment]
Ah non, je ne connais pas du tout le code de SPIP+seenthis, désolé

**Comment by Fil** [comment]
pas de souci; au passage il faudra aussi vérifier les champs `message-id` et `in-reply-to`, car il me semble que l'affichage des mails par fil de discussion ne fonctionne pas (plus?)

**Comment by brunob** [comment]
Chez moi les messages s'affichent bien en thread, du coup le messageèid et le in-reply-to doivent être bons, du coup, pensez-vous que l'ajout du Re dans le sujet soit nécessaire ?

**Comment by Fil** [comment]
"Chez moi" (c-à-d sur l'interface Gmail), ce n'est pas regroupé. Le sujet est le titre _de la réponse_, et je pense que GMail regrouperait sur "Re: " + titre du message initial. Mais c'est un peu un cas à part.

**Comment by brunob** [comment]
Ha, en tout cas j'ai bien ce qui suit pour un message et sa réponse : 

```
Message-Id: <541181@seenthis.net>
```

```
Message-Id: <541282.a7a12846784f5cc50c3a5a35cb394ee7@seenthis.net>
In-Reply-To: <541181@seenthis.net>
```

Manque plus que le `Re:` dans le sujet donc...

**Comment by brunob** [comment]
et hop `"Re: " + titre du message initial` en place
