### ISSUE TITLE
Date de création des comptes

### ISSUE THREAD

**Issue by pick-a-chu** [seenthis/seenthis_squelettes#133]
Est-ce qu'on pourrait afficher le jour de création d'un compte sur son profil ? Je trouve ça très utile pour reconnaître les comptes qui sont créés au moment d'une discussion (notamment pour troller) des comptes inactifs qui se réveillent au cours d'une discussion

**Comment by brunob** [comment]
@pick-a-chu c'est possible avec le plugin date_inscription http://contrib.spip.net/Date-d-inscription mais pour cela il aurait fallu l'activer dès le début. Maintenant que le site est lancé, il faudrait fourber pour pouvoir renseigner la date d'inscription des auteurs existants...

**Comment by Fil** [comment]
Comme approximation on dispose de la date du premier message publié, qu'on peut retrouver en cliquant sur le profil. À mon sens ça suffit pour répondre à la demande.
