### ISSUE TITLE
permettre de ne pas indexer dans spip_me_recherche

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#136]
Quand on utilise seenthis-sphinx, l'indexation des contenus dans spip_me_recherche est inutile. On pourrait la désactiver (sans complications) en évitant de stocker les contenus dans cette table. Pour cela est-ce qu'on introduit un define qu'on teste avant https://github.com/seenthis/seenthis/blob/master/seenthis_options.php#L787 ? c'est un peu sale peut-être.

**Comment by Fil** [comment]
en attendant mieux je peux me contenter de `delete from spip_me_recherche` dans les grosses bases.

J'ai fait quelques essais et je confirme en tout cas que cette table n'est PAS utilisée lorsqu'on est sur sphinx ; le plugin FULLTEXT non plus n'a pas grand intérêt dans ce scénario, et peut être désactivé sans dommages.

**Comment by brunob** [comment]
Si j'ai bien compris indexer_me() ne sert à rien si on utilise sphinx ? Dans ce cas, on pourrait pas tout simplement lui faire renvoyer false (ou une autre valeur plus appropriée) dès le début si le define est actif ?

**Comment by Fil** [comment]
Ah oui tu as raison, le bloc qui précède sert à aller chercher les tags automatiques (opencalais) pour les ajouter dans spip_me_recherche, lequel n'est plus utilisé.
Au passage je m'aperçois que les tags opencalais ne sont sans doute pas indexés dans la version sphinx.

**Comment by brunob** [comment]
Bien, je vais proposer un patch qui va dans cette direction, maintenant le plus "compliqué" ^^, quel nom donner à ce define ? `_SEENTHIS_NO_INDEX` ? (bof, me semble trompeur)
