### ISSUE TITLE
from foireux dans les notifications mail

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#137]
```
From: Le@seenthis.net, Taurillon@seenthis.net,
    magazine eurocitoyen (taurillon) - SeenThis <no-reply@epoxit.com>
```

(sans doute à cause de la virgule dans le nom de l'utilisateur)

(à voir si utiliser Facteur permet de contourner le pb)

**Comment by brunob** [comment]
**Todo** tester le résultat de la chaîne suivante dans le from `Le Taurillon, magazine eurocitoyen (taurillon) - SeenThis <no-reply@epoxit.com>` pour inc/envoyer mail **avec et sans facteur**.

**Comment by brunob** [comment]
@Fil je viens de tester en 3.x et 2.1 sans réussir à reproduire le bug en question, tu l'observes toujours ?

**Comment by Fil** [comment]
La dernière observation en date c'était avant-hier : 
```
Message-Id: <541995.896da85cf07470609b111e5a81b5f9cf@seenthis.net>
In-Reply-To: <541878@seenthis.net>
From: BCE@seenthis.net, 106@seenthis.net, "6 Mhz (bce_106_6) - SeenThis" <no-reply@seenthis.net>
Date: Sun, 13 Nov 2016 21:30:10 +0100 (CET)
```

**Comment by brunob** [comment]
Haaaa trouvé ! il manque des quotes autour des noms des auteurs pour échapper les virgules dans l'api de notification cf : 

http://stackoverflow.com/questions/15555563/how-to-format-an-email-from-header-that-contains-a-comma
http://www.sitepoint.com/forums/showthread.php?461034-Possible-to-escape-a-comma-in-an-email-address&p=3293576&viewfull=1#post3293576

> you must put quotes around the name. This is not the case; multi-word names are allowed without quotes, though if you include punctuation such as commas or periods, then the quotes are required; hence, in the above example, you need the quotes because of the period after the initial "Q". It's never invalid to include the quotes even if they're not required in a given case. 

http://mailformat.dan.info/headers/from.html

Le patch suivant semble bien régler le problème : 

```diff
diff --git a/inc/seenthis_notifier.php b/inc/seenthis_notifier.php
index 52313b3..79904bf 100644
--- a/inc/seenthis_notifier.php
+++ b/inc/seenthis_notifier.php
@@ -267,8 +267,8 @@ function notifier_me($id_me, $id_parent) {
 	if (isset($id_dest)) {
 		$seenthis = $GLOBALS['meta']['nom_site'];
 		mb_internal_encoding("UTF-8");
-		$from = mb_encode_mimeheader(str_replace('@', '', $nom_auteur).' - '. lire_meta('nom_site'), "UTF-8", "Q")
-			. " <no-reply@" . _HOST .">";
+		$from = mb_encode_mimeheader('"'. str_replace('@', '', $nom_auteur) .' - '. lire_meta('nom_site'), "UTF-8", "Q")
+			. "\" <no-reply@" . _HOST .">";
 
 		$headers = "Message-Id: <$id_me" . "@" . _HOST . ">\n";
```

Par contre, il faudrait peut-être ajouter une sécurité pour échapper les éventuelles double quotes dans le nom de l'auteur au cas où...

**Comment by brunob** [comment]
Patch à jour si on souhaite échapper les éventuels guillemets dans les nom d'auteur pour qu'ils s'affichent bien : 

```diff
diff --git a/inc/seenthis_notifier.php b/inc/seenthis_notifier.php
index 52313b3..8bb4e1e 100644
--- a/inc/seenthis_notifier.php
+++ b/inc/seenthis_notifier.php
@@ -267,8 +267,8 @@ function notifier_me($id_me, $id_parent) {
 	if (isset($id_dest)) {
 		$seenthis = $GLOBALS['meta']['nom_site'];
 		mb_internal_encoding("UTF-8");
-		$from = mb_encode_mimeheader(str_replace('@', '', $nom_auteur).' - '. lire_meta('nom_site'), "UTF-8", "Q")
-			. " <no-reply@" . _HOST .">";
+		$from = mb_encode_mimeheader('"'. str_replace('"', '\"', str_replace('@', '', $nom_auteur)) .' - '. lire_meta('nom_site'), "UTF-8", "Q")
+			. "\" <no-reply@" . _HOST .">";
 
 		$headers = "Message-Id: <$id_me" . "@" . _HOST . ">\n";

```

**Comment by Fil** [comment]
>
> + $from = mb_encode_mimeheader('"'. str_replace('"', '\"',
> str_replace('@', '', $nom_auteur)) .' - '. lire_meta('nom_site'), "UTF-8",
> "Q")


cool

sans vouloir être pédant je mettrais plutôt '\\"' que '\"' c'est plus clair
sur ce que l'on veut.

-- Fil

**Comment by brunob** [comment]
Envoyé et poussé en prod, wait & see pour les retours :)

**Comment by brunob** [comment]
Et comme souvent, le ty oups qui va avec cf seenthis/seenthis@46ff12f9eaf1cddebb3a65336e3df7abf7bbddbd
