### ISSUE TITLE
readability ne trouve pas le contenu de seenthis

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#14]
si l'on en croit l'expérience de @tetue
https://twitter.com/tetue/status/308268639545614336

**Comment by brunob** [comment]
Si readability est bien l'outil utilisé par firefox pour le mode lecture, ça s'affiche très bien sous à ce jour :

![read](https://user-images.githubusercontent.com/418064/55503934-fdaeb080-564f-11e9-95cd-29cb94c516e0.png)

Si on parle de https://www.readability.com/ => Readability is no longer available.

On ferme ?
