### ISSUE TITLE
mixed-content sur https

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#140]
> Mixed Content: The page at 'https://epoxit.com/recherche?recherche=%2Bcuba+%2Binternet' was loaded over HTTPS, but requested an insecure image 'http://img.youtube.com/vi/IudOxP4MQnA/0.jpg'. This content should also be served over HTTPS.

(je ne vois pas trop qu'on ait de solution générique à ça… mais pour les liens générés par OEmbed ça doit pouvoir se régler au cas par cas)

**Comment by brunob** [comment]
Maintenant qu'on a migré, qu'on force le https et que tu as corrigé autoembed (merci !), on doit pouvoir fermer le ticket non ?

**Comment by Fil** [comment]
on peut fermer mais il faudra peut-être réouvrir : je crois qu'il ya dans certains cas des img qui ne sont pas recopiées en local/
