### ISSUE TITLE
SPIP 3 : problème ajax formulaire_poster_message

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#147]
Toujours dans mon chantier de passage en SPIP 3, j'ai un comportement que je n'arrive pas à expliquer sur le formulaire_poster_message de la têtière. Le post du message se passe bien, la liste en dessous est bien mise à jour, mais le champ texte du formulaire est masqué par jQuery, donc pas moyen de poster un autre message à la suite.

Chose étonnante, ça fonctionne très bien avec le même formulaire utilisé pour répondre à un message.

J'ai fouillé dans les logs et les tickets de core.spip.net, mais rien trouvé de ressemblant...

@seenthis/commiters quelqu'un aurait-une piste pour ce bug ?

**Comment by brunob** [comment]
7c6d921da5450cc17a79820c2df7b695245229f8 règle le problème :)

**Comment by Fil** [comment]
je ne suis pas certain d'avoir compris : c'était lié à SPIP 3 ?  Ou c'est un comportement de seenthis qui va changer ?

**Comment by brunob** [comment]
D'après ce que j'en ai compris, le `hide()` que j'ai retiré n'était pas appliqué au retour du formulaire en 2.1, mais il l'était en 3.0 suite à la modification 331fa1e01ef8aa27f4d0db328734d626bc947c6f (qui permet d'éviter une erreur js au retour du form).

Pour conclure, aucun changement de comportement, j'ai bien comparé sur mes deux instances de seenthis (2.1 et 3.0).

**Comment by Fil** [comment]
marrant cette histoire de bug dans le bug

**Comment by brunob** [comment]
Oui, c'est marrant une fois qu'on a trouvé l'origine du problème, mais je rigolais pendant les quelques heures passées à fouiller dans les différentes js du squelette alors que le bug était tout simplement dans le formulaire :p
