### ISSUE TITLE
plantage (par moments) de la boucle opencalais sur la page d'accueil

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#149]
![capture d ecran 2016-04-24 12 23 02](https://cloud.githubusercontent.com/assets/7001/14766823/b47200e8-0a17-11e6-8870-a9a579bf4367.png)

constaté au passage deux fois ces derniers jours (ça n'apparaît que parce que je suis admin), un reload et ça disparaît

**Comment by brunob** [comment]
La description du problème et le fait que celui-ci disparaisse au rechargement me rappelle ce que j'obtiens de mon côté aussi bien en 2.1 qu'en 3.0. Chez moi le bug apparaît sur la page d'un tag quand je suis connecté en tant qu'admin, cf capture ci-dessous : 

![furtive](https://cloud.githubusercontent.com/assets/418064/14895307/5149d39c-0d78-11e6-9875-e4a5a2c08d8f.png)

Chelou n'est-ce pas ?

**Comment by Fil** [comment]
similaire (ou pas?) cette erreur sur tag(60) que MySQL prend pour une fonction `tag` argument `60`
![capture d ecran 2016-07-02 11 13 16](https://cloud.githubusercontent.com/assets/7001/16539546/d64072a8-4046-11e6-8e2f-272c8a964a24.png)

**Comment by brunob** [comment]
Pour info, l'index préfixé cf http://dev.mysql.com/doc/refman/5.7/en/column-indexes.html a été ajouté par seenthis/seenthis@52bd62647d166a701e25441a079e78e176c70d89

Après recherches, je n'ai rien trouvé à propos de ce genre d'erreur sur http://bugs.mysql.com

**Comment by brunob** [comment]
De ce que j'en ai lu, ce type d'index permet d'optimiser l'espace disque utilisé : 

> Potential advantages to using partial indexes is that if the values in the indexed field tend to differ in the first 10 characters, this index should not be much slower than an index created from the entire post_text column. At the same time, using column prefixes for indexes can make the index file much smaller, which could save a lot of disk space and may also speed up table inserts.

http://www.databasejournal.com/features/mysql/article.php/3840606/Maximizing-Query-Performance-through-Column-Indexing-in-MySQL.htm

Mais il semble que cela pose problème dans un `GROUP BY` : 

> With all the goodness that partial indexes offer, I have found at least one draw back. It seems that partial indexes cannot be used with aggregation functions like GROUP BY.

https://theonblog.com/2011/06/28/on-mysql-partial-indexes/

Et cela peut avoir un effet contre productif dans certains cas : 

> with the partial index, the engine doesn't know the value of the referrer_host until it looks at the record. It has to scan the whole table! t could end up being even slower, because a table scan will at least be a sequential read.

http://stackoverflow.com/a/8016285

Perso, je ne comprends pas plus et je n'arrive pas à exécuter la requête suivante sans erreur avec MariaDB 10.1.21 : 

```sql
SELECT me_tags.date, L1.id_parent, me_tags.id_me FROM spip_me_tags AS `me_tags` INNER JOIN spip_me AS L1 ON ( L1.uuid = me_tags.uuid ) WHERE (me_tags.tag like '#octodo%') GROUP BY me_tags.uuid,me_tags.id_me,me_tags.tag(60),me_tags.class,me_tags.tag(255) ORDER BY me_tags.date DESC LIMIT 0,150
```

@archiloque tu peux nous éclairer sur ce point ?

**Comment by brunob** [comment]
Le fix que j'ai envoyé règle bien le problème, et après installation d'un seenthis en 3.1 je n'ai plus ces satanés index sur la table spip_me_tags.

Je pense même que l'index `spip_me_tags_index_tags` qui était présent dans le fichier sql du repo ne devait pas être créé par SPIP, puisque la procédure d'upgrade pour le supprimer générait une belle erreur SQL du type `ALTER TABLE `spip_octopouce`.spip_me_tags DROP INDEX `spip_octopouce`.spip_me_tags_index_tags`.

Case closed pour moi, le ticket sera fermé automatiquement quand la branche 3.1 sera fusionnée dans master.

**Comment by brunob** [comment]
Il faudra revenir sur cette modification cf https://github.com/seenthis/hebergement/issues/12#issuecomment-333330053

Après quelques recherches supplémentaires, je remarque que l'index en question fait que SPIP génère une requête erronée que l'index soit déclaré via SPIP ou créé directement dans la base. La bonne requête devrait être (à confirmer) : 

```sql
SELECT me_tags.date, L1.id_parent, me_tags.id_me FROM spip_me_tags AS `me_tags` INNER JOIN spip_me AS L1 ON ( L1.uuid = me_tags.uuid ) WHERE (me_tags.tag like '#octodo%') GROUP BY me_tags.uuid,me_tags.id_me,me_tags.tag,me_tags.class,me_tags.tag(255) ORDER BY me_tags.date DESC LIMIT 0,150
```

J'en ai profité pour vérifier que la valeur `60` convienne bien à notre base et ça me semble bon : 

```sql
MariaDB [seenthis]> SELECT
    ->     COUNT(DISTINCT tag),
    ->     COUNT(DISTINCT LEFT(tag, 5)),
    ->     COUNT(DISTINCT LEFT(tag, 10)),
    ->     COUNT(DISTINCT LEFT(tag, 20)),
    ->     COUNT(DISTINCT LEFT(tag, 40)),
    ->     COUNT(DISTINCT LEFT(tag, 60)),
    ->     COUNT(DISTINCT LEFT(tag, 80))
    -> FROM
    ->     spip_me_tags;
+---------------------+------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+
| COUNT(DISTINCT tag) | COUNT(DISTINCT LEFT(tag, 5)) | COUNT(DISTINCT LEFT(tag, 10)) | COUNT(DISTINCT LEFT(tag, 20)) | COUNT(DISTINCT LEFT(tag, 40)) | COUNT(DISTINCT LEFT(tag, 60)) | COUNT(DISTINCT LEFT(tag, 80)) |
+---------------------+------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+
|              974355 |                        27509 |                        125335 |                        380191 |                        722144 |                        918035 |                        956329 |
+---------------------+------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+
1 row in set (53.57 sec)
```

Réf http://www.rndblog.com/how-to-determine-the-leading-prefix-part-of-a-mysql-index/

**Comment by brunob** [comment]
Le bug était bien dans SPIP, il est maintenant corrigé avec l'aide de @marcimat merci tout plein à lui :)

https://core.spip.net/projects/spip/repository/revisions/23737 dans le trunk et https://core.spip.net/projects/spip/repository/revisions/23738 en 3.1

Reste plus qu'à annuler la modification de https://github.com/seenthis/seenthis/commit/c309351d1068b7f29832dc6b2af0e4108487ea50 et on devrait enfin pouvoir fermer ce ticket :)

Pour info, je vais simplement annuler la suppression de l'index dans l'upgrade du plugin au lieu de supprimer/recréer, ça ne devrait pas impacter grand monde puisque je pense être le seul à utiliser la branche 3.1.
