### ISSUE TITLE
notifier_me quand quelqu'un utilise un tag qu'on suit

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#151]
Je viens juste de remarquer qu'on ne reçoit pas de notification quand quelqu'un qu'on ne suit pas poste un message comportant un tag qu'on suit. Du coup, le seul endroit où l'on peut voir ce genre de post est sur la page d'accueil quand on est logué.

Ne serait-il pas judicieux de notifier les personnes abonnées à un tag dans ce cas ? En fonction de l'activation d'une option dans les préférences ?

Je demande ici dans un premier temps, mais si vous préférez j'ouvre la discussion dans un post sur seenthis.

**Comment by brunob** [comment]
En attendant, je propose d'ajouter un pipeline seenthis_notifierme_destinataires dans le plugin seenthis pour permettre d'ajouter des destinataires aux notifications envoyées lors d'un post, cf patch ci-dessous : 

```diff
diff --git a/inc/seenthis_notifier.php b/inc/seenthis_notifier.php
index 52b04a1..4a3f9b1 100644
--- a/inc/seenthis_notifier.php
+++ b/inc/seenthis_notifier.php
@@ -256,6 +256,13 @@ function notifier_me($id_me, $id_parent) {
 		$id_dest[] = $id_auteur_me;
 	}
 
+	$id_dest = pipeline('seenthis_notifierme_destinataires',
+		array(
+			'args'=>array('id_me'=>$id_me,'id_parent'=>$id_parent),
+			'data'=>$id_dest
+		)
+	);
+
 	// Envoyer si besoin
 	if (isset($id_dest)) {
 		$seenthis = $GLOBALS['meta']['nom_site'];
diff --git a/paquet.xml b/paquet.xml
index 71e119e..5585237 100644
--- a/paquet.xml
+++ b/paquet.xml
@@ -13,6 +13,7 @@
 	<auteur>ARNO*</auteur>
 
 	<pipeline nom="affichage_final" />
+	<pipeline nom="seenthis_notifierme_destinataires" action="" />
 	<pipeline nom="declarer_tables_interfaces" inclure="base/seenthis.php" />
 	<pipeline nom="declarer_tables_principales" inclure="base/seenthis.php" />
 	<pipeline nom="declarer_tables_auxiliaires" inclure="base/seenthis.php" />
```

**Comment by brunob** [comment]
Voir https://github.com/seenthis/seenthis/commit/15805929440f77f729319ad8d00d9d43487b2084

/me mode boulet qui s'est trompé de numéro pour la référence au ticket

**Comment by Fil** [comment]
Je réponds un peu à côté avec #159.

**Comment by brunob** [comment]
Je pense qu'on peut fermer le ticket maintenant que c'est possible de passer par le pipeline `seenthis_notifierme_destinataires` pour ce genre d'ajout.

**Comment by Fil** [comment]
je pense qu'il faut laisser ouvert : on a le mécanisme mais la fonctionnalité reste manquante

**Comment by brunob** [comment]
Pour ce qui est de la fonctionnalité, je l'ai implémenté das octopouce, c'est plutôt simple : 

`php
 /**
 * Insertion dans le pipeline seenthis_notifierme_destinataires (Plugin seenthis)
 * Ajouter aux destinataires des notifications les personnes qui suivent les tags présents dans le post
 * 
 * @pipeline seenthis_notifierme_destinataires
 * @param array $flux Données du pipeline
 * @return array      Données du pipeline
 */
function octopouce_seenthis_notifierme_destinataires($flux){
	$texte = texte_de_me($flux['args']['id_me']);

	// auteurs abonnés aux tags cités dans le message ;
	include_spip('inc/traiter_texte');
	$t = preg_replace("/"._REG_URL."/ui", "", $texte);
	if (preg_match_all("/"._REG_HASH."/ui", $t, $tags)) {
		foreach(array_unique(array_values($tags[0])) as $tag) {
			$tag = implode('|', explode('_', substr($tag, 1)));
			$query_follow = sql_select("id_follow", "spip_me_follow_tag", "tag REGEXP '$tag'");
			while ($row_follow = sql_fetch($query_follow)) {
				$flux['data'][] = $row_follow['id_follow'];
			}
		}
	}

	return $flux;
}
`

À voir si on intègre ça dans la branche 3.x...

**Comment by Fil** [comment]
Attention ton code ci-dessus est valable pour les tags chelous d'octopouce, découpés par les _

pourquoi pas effectivement l'ajouter dans seenthis (avec un REGEXP ^$tag, et une option pour s'en désabonner)

**Comment by brunob** [comment]
Oui, le traitement est spécifique aux poulpes, mais c'est surtout pour montrer la simplicité de l'ajout ;)

**Comment by brunob** [comment]
Ça devrait être bon avec les deux derniers commits listés ici, à tester sur la version de dev. On peut fermer le ticket amha.

**Comment by brunob** [comment]
Je reviens là dessus car je découvre pas mal d'erreur sql dans les logs cf : 

```
2020-07-01 19:07:14 217.182.178.243 (pid 24356) :Pub:ERREUR: Erreur 1064 de mysql: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ignorance' /* /spip.php?action=cron + 217.182.178.243 */' at line 3
in /srv/stdev.zoo-logique.org/public_html/plugins/seenthis/inc/seenthis_notifier.php L260 [sql_select(),notifier_me(),queue_start_job(),queue_schedule(),inc_genie_dist(),cron(),action_cron(),traiter_appels_actions(),include()]
SELECT id_follow
FROM `stdev`.spip_me_follow_tag
WHERE tag REGEXP '^#fabrique_de_l'ignorance'
```

@fil la regex que tu proposais pose problème quand le tag contient une apostrophe, il doit juste manquer un échappement...

**Comment by Fil** [comment]
Ah oui et ça sent pas bon en termes de sécurité ça…

**Comment by brunob** [comment]
`$query_follow = sql_select('id_follow', 'spip_me_follow_tag', "tag REGEXP ". sql_quote('^' . $tag));` devrait le faire, testé chez moi, je teste en prod pour voir...
