### ISSUE TITLE
Variante squelette mot_fin obsolète

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#153]
Salut, je remarque que le squelette en question utilise la boucle mots et n'affiche rien cf http://seenthis.net/tag/spip$ ; ne serait-il pas obsolète ?

https://github.com/seenthis/seenthis_squelettes/blob/master/noisettes/contenu/contenu_mot_fin.html#L14

On peut le virer du coup ? Et supprimer la partie correspondante dans les urls de seenthis ?

https://github.com/seenthis/seenthis/blob/master/urls/seenthis.php#L122

Autre point, le squelette mot_flou semble fonctionnel, mais est-il encore utile ?

http://seenthis.net/tag/spip*

**Comment by Fil** [comment]
Je préférerais qu'on puisse le réparer car c'est assez utile (pour chercher
#bio sans avoir #biographie).

**Comment by brunob** [comment]
Ok, je regarde ça asap :)

**Comment by brunob** [comment]
Ha, chelou, l'introduction de la boucle mots dans le squelette en question vient de cette modification : 

https://github.com/seenthis/seenthis_squelettes/commit/8032c35d68a59a360d2686e6a1fbc60f9b9cfb34#diff-05b5ff21857447fa09da8119ab18353c

Mais le log ne me permet pas de deviner pourquoi, peut-être que @archiloque pourra nous en dire plus ?

**Comment by brunob** [comment]
et hop, patch proposé, avec un r en trop dans le log, sorry...

**Comment by Fil** [comment]
appliqué en #154
