### ISSUE TITLE
lien + tag dans les notifications => problème

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#163]
> I noticed that almost every time that I receive and automatic email from seenthis when a person put me in copy that the link of the page that is quoted in the post is glued with the first keyword (tag).
> This thing makes the link invalid and you have to correct it manually on the browser address line or to go the original post page and check the link from there.
> 
> Have a look at the attached images.
> 
> I think should be enough to add a white line in the script to separate the link line from the tag line.

![schermata 2016-07-20 alle 09 46 25](https://cloud.githubusercontent.com/assets/7001/16979838/9a92a0ac-4e63-11e6-84dc-5609af0d0363.jpg)
![schermata 2016-07-20 alle 09 57 12](https://cloud.githubusercontent.com/assets/7001/16979839/9a9506da-4e63-11e6-9090-022470301854.jpg)

**Comment by Fil** [comment]
Autre solution faire de beaux mails de notifs en HTML (comme @7h36)

**Comment by brunob** [comment]
On a testé les mails html et ça n'a pas eu succès (et j'ai bien galéré avec le plugin facteur pour focer l'envoi au format txt). Est-ce que le bug est encore d'actualité ?

**Comment by brunob** [comment]
Je viens de tester avec le contenu du message cité, je ne reproduis ni dans la notification originale, ni dans celle que je me suis fowardé. Le lien est le bon dans un mail affiché en texte brut dans thunderbird. On ferme ?
