### ISSUE TITLE
demander aux robots "flux rss" de se revalider

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#164]
à propos des robots je crois qu'il faudrait demander qu'ils se connectent une fois tous les 3 ou 6 mois pour revalider leur flux

en gros si date dernière connexion > 6 mois on débranche le flux et on envoie un mail disant "hello, il faut te connecter si tu veux continuer à envoyer du contenu"

**Comment by Fil** [comment]
-[ ] wording du message
-[ ] comment noter en bdd qu'un flux est désactivé
-[ ] interface pour réactiver / savoir qu'on est réactivé (email ?)

**Comment by brunob** [comment]
Huhu, j'allais le faire à la bourrin en vidant le champ url du flux tous les X mois (X étant un define) si le champ en_ligne de l'auteur est inférieur à la durée prévue.

Du coup, ça complique un peu le plan, je vais y réfléchir...

**Comment by Fil** [comment]
on peut faire bourrin en mettant une étoile devant le http, ça bloquera les updates ; mais tout virer c'est pas sympa ça oblige à rechercher l'adresse du flux qu'on avait mis

**Comment by brunob** [comment]
J'ai envoyé un début de génie pour répondre à la demande, reste à affiner le délai, le nombre d'items à traiter à chaque passe et le texte du mail.

**Comment by brunob** [comment]
seenthis/seenthis_importer_flux@0297d9a91d448ab505c3bf9ab90c66a2dcbcc72a devrait permettre d'exclure les flux désactivés dans genie_seenthis_importer_flux() histoire de ne pas boucler dessus pour rien.

**Comment by brunob** [comment]
Voilà, j'ai ajouté la notification avec seenthis/seenthis_importer_flux@8e326995f214795b42cdf531c990c9291f33c09d et voici ce que je propose d'ajouter dans les chaînes de langue de seenthis_squelettes : 

```php
	'flux_desactive_titre' => 'Import de votre flux désactivé sur @nom_site@',
	'flux_desactive_texte' => 'Bonjour @nom@,
	L’import automatique de votre flux RSS/ATOM a été désactivé car cela fait un moment que vous ne vous êtes pas connecté au site.
	Vous pouvez l’activer de nouveau en supprimant l’étoile présente au début de son adresse depuis la page préférences.',
```

J'ai un doute pour **depuis la page préférences** car dans les autres notifications on cause de **vous pouvez régler vos préférences dans votre profil** mais je ne trouve pas ça terrible car le lien qui pointe vers la page est bien intitulé **préférences**... Bref, à discuter :)

**Comment by Fil** [comment]
Vous pouvez le réactiver depuis votre page de préférences, en supprimant
l’étoile ajoutée au début de son adresse.

**Comment by brunob** [comment]
Merci pour le retour @Fil j'ai envoyé tout ça dans seenthis/seenthis_squelettes#165 et seenthis/seenthis_importer_flux#2

**Comment by BoOz** [comment]
si url_flux commence par *
afficher le message aussi dans la page paramètres

**Comment by brunob** [comment]
Il serait peut-être intéressant de ne pas utiliser le champ en_ligne pour tout ça cf https://core.spip.net/issues/3480#note-7 et donc utiliser le plugin https://git.spip.net/spip-contrib-extensions/date_connexion qui est fait pour ça ?
