### ISSUE TITLE
authentification XMPP

### ISSUE THREAD

**Issue by jerome-poisson** [seenthis/seenthis_squelettes#166]
Ça serait chouette d'avoir l'authentification XMPP sur SeenThis ou mieux Spip directement. Avec un composant, ça serait juste une requête HTTPS à faire, possiblement sur un serveur déjà installé (c.-à-d. rien à faire pour l'admin à part spécifier l'URL).

L'idée serait d'avoir un champ "authentification XMPP" avec just un jid à mettre (du type pseudo@serveur.tld), appuyer sur un bouton et attendre la réponse de la requête HTTPS, tout le boulot étant fait par le composant et le client.

Plus d'infos et lien vers un composant fonctionnel : http://linuxfr.org/news/authentifiez-vous-sans-mot-de-passe-grace-a-xmpp

**Comment by brunob** [comment]
@jerome-poisson ça me semble plus malin d'en faire un plugin pour SPIP, ainsi ça pourrait servir sur d'autres SPIP que seenthis :) (et si un jour ce plugin est dispo, on l'active sur seenthis et on ajoute le champ qui va bien dans le formulaire de la page profil).

amha on peut fermer le ticket ici, c'est plutôt à voir du côté de la zone de SPIP https://git.spip.net/spip-contrib-extensions
