### ISSUE TITLE
bug de cron dans le mail de 7h36

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#168]
au bas du mail de 7h36 du dimanche 11.09.16, on voit indiqué
```
Erreur...
Fichier seenthis_desactiver_flux introuvable
```

La manière dont fonctionne 7h36, c'est une page web que j'appelle de l'extérieur, depuis un script sur alan. Donc à ce moment-là côté seenthis ça appelle le cron, et ça pouiche.

**Comment by brunob** [comment]
Ha oui, je pense qu'il faudrait déplacer la fonction `seenthis_desactiver_flux()` dans un fichier éponyme car je lis ça dans le phpdoc de `inc_genie_dist()` : 

_Le fichier homonyme du repertoire "genie/" est automatiquement lu et il est supposé définir cette fonction._

Je regarde si ce "supposé" est contournable, sinon je déplacerai la fonction dans un fichier à part...

**Comment by brunob** [comment]
@Fil voilà ça devrait être réglé, j'ai up sur le serveur, on verra ce que ça donne demain matin :)
