### ISSUE TITLE
cron des imports de flux RSS

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#172]
https://github.com/seenthis/seenthis_importer_flux/blob/7f3cbfd661cda5abcd589718304715e1698c8838/seenthis_importer_flux_pipelines.php#L7

```
	// duree du cron a moduler en fonction du nombre de flux...
	// pour le moment, on en prend un au hasard à chaque tour
	$taches_generales['seenthis_importer_flux'] = 10;
	// désactiver le flux des auteurs qui ne se sont pas logués depuis 6 mois
	$taches_generales['seenthis_desactiver_flux'] = 10;
```

Le premier est sans doute trop lent, car maintenant on a beaucoup d'utilisateurs à flux, et c'est souvent très en retard. Une option que j'avais prévue était de passer plusieurs RSS par tour de cron… on fait ça ? Un define ?

Le second est sans doute (beaucoup!) trop souvent.

ping @brunob

**Comment by Fil** [comment]
Le define permettrait de modifier le limit à la fin de cette requête =
https://github.com/seenthis/seenthis_importer_flux/blob/master/genie/seenthis_importer_flux.php#L10

**Comment by Fil** [comment]
Il ne faut pas trop monter ce define, sinon le pauvre utilisateur qui tombe par hasard sur 10 chargements de flux va attendre sa page longtemps. Je pense qu'il faut qu'on augmente le rythme (??)

**Comment by brunob** [comment]
@Fil ouep, comme tu le dis il vaut mieux jouer sur la fréquence que sur le nombre de flux traités à chaque tour.

**Comment by brunob** [comment]
@Fil on en est où avec ce ticket ? On peut fermer ?

**Comment by Fil** [comment]
Je ne crois pas que ça a changé…

**Comment by brunob** [comment]
@Fil voilà j'ai ajouté deux defines pour ça dans la branche spip31, dis moi si leur nom ne te convient pas, et hop on ferme :)

**Comment by brunob** [comment]
Arf je me suis vautré complet dans le nom, c'est pas le nombre mais le délai qu'on passe, je corrige ça.

**Comment by Fil** [comment]
pour la recherche des utilisateurs pas logués depuis 6 mois, je crois qu'on peut le faire toutes les 24h plutôt que toutes les 10 secondes :)

**Comment by brunob** [comment]
Voilà c'est fait, avec un ty oups pour la forme :p

/me levé trop tôt
