### ISSUE TITLE
Message privé à un auteur

### ISSUE THREAD

**Issue by nd-** [seenthis/seenthis_squelettes#175]
Proposition d'évolution : pouvoir envoyer un message privé à un auteur, soit depuis sa page auteur, soit directement sur un post ou un commentaire en particulier (plus utile).
Réservé aux personnes connectées pour éviter le spam, oeuf corse.

**Comment by Fil** [comment]
doublon https://github.com/seenthis/seenthis_squelettes/issues/118

**Comment by gaetan19** [comment]
salut
