### ISSUE TITLE
ne pas créer de player sur les sons en http, seulement https

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#176]
cf. https://seenthis.net/messages/572384

**Comment by Fil** [comment]
une autre solution serait d'avoir un proxy sur seenthis, mais ça risque de poser de nouvaux problèmes

**Comment by brunob** [comment]
Est-ce que que ça vaut toujours le coup d'ajouter une exception pour ça aujourd'hui maintenant que la plupart des sites sont accessibles en https ?

**Comment by brunob** [comment]
Ça se passe là https://zone.spip.org/trac/spip-zone/browser/spip-zone/_plugins_/plugins_seenthis/autoembed/autoembed.php#L134 il suffit de retirer le ? après https pour que l'embed des mp3 n'ait lieu que si le site source est en https.

Si on souhaite être sympa avec les sites qui sont encore en http, on pourrait conditionner la modification sur un test simple comme `(!empty($_SERVER["HTTPS"]) and $_SERVER["HTTPS"] == 'on')` même si ça ne matchera pas tous les cas possibles. Sinon, si on considère que autoembed est forcément lié à seenthis on peut directement tester la constante `_HTTPS`.

Vos avis ?

**Comment by brunob** [comment]
Devrait être corrigé par https://github.com/seenthis/seenthis_squelettes/issues/176 que je pousse en prod dans la foulée.
