### ISSUE TITLE
marquage des posts envoyés par RSS

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#177]
Il me semble que les posts envoyés par RSS devraient être marqués comme tels dans la base (et peut-être dans l'interface, mais là je ne sais pas) ; par ailleurs actuellement ils ont un IP qui correspond à celui du visiteur qui a déclenché le cron, et ça c'est mauvais à tout point de vue.

**Comment by brunob** [comment]
Côté front, on pourrait ajouter ça dans la span class auteur située en bas de chaque message, avec une mention simple du style : `@dede via RSS` et l'url du flux en question serait affichée survol du terme RSS. Vos avis ?

Côté base, il faudrait ajouter un champ dans la table des posts, comme souvent le plus chiant est de bien le nommer, je propose `via_rss` ou `viarss`. D'autres propositions ?

**Comment by brunob** [comment]
Et hop, c'est proposé, testé & approuvé sur mon instance local, à vos commentaires et +1 dans les différentes PRs.

**Comment by brunob** [comment]
Mergé, poussé en prod, on ferme.

**Comment by brunob** [comment]
Et c'est visible ici par exemple : https://seenthis.net/messages/886955

J'ai peut-être fermé le ticket trop vite, car il reste la seconde partie cf : 

> par ailleurs actuellement ils ont un IP qui correspond à celui du visiteur qui a déclenché le cron, et ça c'est mauvais à tout point de vue.

J'ouvre de nouveau, mais le fix est simple, maintenant qu'on sait qu'un post est envoyé viarss dans `instance_me()` on peut unset l'IP dans ce cas et zou. Ça t'irait @Fil ?

**Comment by Fil** [comment]
ouip

**Comment by brunob** [comment]
Ha mince, le champ IP est en ``ip` varchar(40) NOT NULL,` du coup ça ne passera peut-être pas si on colle une valeur vide, je teste, sinon on pourrait y coller `0.0.0.0` ?

**Comment by rastapopougros** [comment]
une chaine vide c'est pas pareil que null, à priori (comme pour tous les champs text not null, on a bien le droit de les laisser vide)

**Comment by brunob** [comment]
thx @rastapopougros alors c'est simple :)

**Comment by brunob** [comment]
Et voilà, c'est commité, je maj en prod dans la foulée.

**Comment by brunob** [comment]
Je reviens là dessus suite à https://github.com/seenthis/seenthis_importer_flux/pull/7#issuecomment-799359167

Cet ajout fait que seenthis ne peut pas fonctionner sans le plugin seenthis_importer_flux puisque la fonctoin instance_me tente de mettre à jour un champ qui n'est pas là si le plugin n'est pas présent => paf erreur sql

Il faut donc amha, ajouter seenthis_importer_flux aux necessites de seenthis, d'autres avis/idées ?

**Comment by cy-altern** [comment]
à priori j'aurais dit que le necessite est la solution la plus "classique"

**Comment by brunob** [comment]
@seenthis/commiters d'autres avis ?

**Comment by rastapopougros** [comment]
J'ai failli dire : soit necessite soit plutôt le plugin "sait utiliser" l'autre et donc fait un if (plugin machin) { ajout }

Mais… en fait je vois que c'est pas juste à l'intérieur de la fonction qu'il y a un ajout, comme là : 47cc4130a3466d58acee71a05c2a4a78a353749a

Mais carrément dans la signature de la fonction ! 2235022e83f86ddc9a2d169880bd5461b2e1318a

Si c'est un ajout de signature, donc dans le cœur même de l'API : ce champ ne peut pas être ajouté par un autre plugin, et donc oui, à priori c'est bien au noyau de l'ajouter dans la base. Donc non pas bof, c'est bien le plus logique dans ce cas là.

**Comment by brunob** [comment]
Et hop, c'est fait, merci pour vos retours :)

**Comment by rastapopougros** [comment]
Moui là bof pour le coup, en  ce qui me concerne, puisque du coup il n'y a strictement aucune logique à ce découpe. Je rappelle que "seenthis_importer_flux" *nécessite* "seenthis" ! Alors si ya l'inverse dans l'autre sens aussi… ce découpage n'a plus aucun sens. :)

**Comment by brunob** [comment]
@rastapopougros tu as bien vu la manière dont est construite la fonction `instance_me` dans seenthis ? En l'état, elle ne permet absolument pas de faire autrement, mais avec une future refonte ça pourrait être amélioré bien sûr. Le but de la modification (en mode patch d'urgence) était d'éviter à quelqu'un qui installe un seenthis en suivant la doc de se retrouver avec un site non fonctionnel qui ne permet pas de poster le moindre message (c'est du vécu ^^).

**Comment by brunob** [comment]
Ha ben ça va te contenter @rastapopougros je vais devoir virer le necessite dans le paquet de seenthis car SVP se vautre complet ne veut pas installer les deux en tombant dans une sorte de boucle de necessites :\ (bref, l'info est dans le fichier d'install, c'est déjà mieux que rien)

**Comment by rastapopougros** [comment]
Haha voilà, SVP aussi il trouve que ça n'a aucune logique un plugin A qui nécessite B, tout en ayant B qui nécessite A :D

**Comment by brunob** [comment]
En y repensant, je commence à me dire que https://github.com/seenthis/seenthis_importer_flux/commit/a5ea70238c520f68f9acf1a6677c0fe8e2a87fa5 était une mauvaise idée, amha ça serait plus propre que ce champ soit déclaré par seenthis (le core) et que le plugin importer flux l'utilise quand il est actif, ainsi on peut revenir à la situation où ce dernier était optionnel.

@seenthis/commiters votre avis ?

**Comment by rastapopougros** [comment]
Plus haut :)
> Si c'est un ajout de signature, donc dans le cœur même de l'API : ce champ ne peut pas être ajouté par un autre plugin, et donc oui, à priori c'est bien au noyau de l'ajouter dans la base.

**Comment by brunob** [comment]
Ha ok, j'avais mal capté la tournure de fin de ton message "Donc non pas bof, c'est bien le plus logique dans ce cas là.", parfait, let's go pour une tournée de revert et migration de code :)

**Comment by brunob** [comment]
PS : dommage que mes pairs ne m'aient pas alerté sur ce point lors des premières relectures :p

**Comment by rastapopougros** [comment]
ouais dsl j'essaye vraiment de lire à chaque fois, pour au moins commenter, mais j'ai pas dû le voir passer la première fois

**Comment by brunob** [comment]
No problemo, voilà deux PRs à relire pour en finir avec ce ticket :)
