### ISSUE TITLE
les # disparaissent dans le flux rss

### ISSUE THREAD

**Issue by gchilloux** [seenthis/seenthis_squelettes#179]
Si l'on poste "#test #test #test" dans seenthis. cela remonte comme il faut, voir [https://seenthis.net/messages/574315](https://seenthis.net/messages/574315)
Par contre dans le flux rss les # ont disparu.
[https://seenthis.net/people/nabaz45/feed_tw](https://seenthis.net/people/nabaz45/feed_tw)

**Comment by brunob** [comment]
en rapport avec #167 ?

**Comment by gchilloux** [comment]
Pour ma part, pas de soucis dans les e-mails, les "#" sont bien présent.

**Comment by brunob** [comment]
@gchilloux ha tiens, ça voudrait dire que le bug signalé dans #167 n'est plus présent. @severo tu confirmes ?

**Comment by severo** [comment]
Confirmé, c'est réparé.

**Comment by brunob** [comment]
\o/ on peut fermer le ticket, merci pour le retour @severo :)

**Comment by rastapopougros** [comment]
Du coup il est à fermer ou bien ?

**Comment by brunob** [comment]
Oui, on ferme, merci pour le rappel.
