### ISSUE TITLE
css foireuses sur android 7

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#180]
signalé par @vincib

---- 

![bug android 7](https://cloud.githubusercontent.com/assets/7001/24645560/e5fd27bc-1918-11e7-993f-da0a848ea720.jpg)

---- 

![bug android 7 2](https://cloud.githubusercontent.com/assets/7001/24645612/22e3faf2-1919-11e7-9fe0-b81f363b46af.jpg)

**Comment by brunob** [comment]
Fort possible, mais il faudrait tester le bug sur la branche 3.1 dans laquelle j'ai corrigé pas mal de bugs côté responsive. Je peux filer l'adresse du site sur lequel je bosse en 3.1 @vincib en privé s'il le souhaite.

**Comment by vincib** [comment]
n'hésitez pas

**Comment by vincib** [comment]
La CSS de ton site de dev marche bien pour mon Android 7 / Firefox (with uBlock) 

note: https://seenthis.net/ est OK mais sur l'url d'origine de @kassem ça déconne

**Comment by brunob** [comment]
@vincib maintenant que seenthis est lui aussi passé en SPIP 3.2 cela doit être corrigé, tu confirmes ?

**Comment by brunob** [comment]
On ferme, ça doit bien être réglé.
