### ISSUE TITLE
Logout immédiat

### ISSUE THREAD

**Issue by Tyrben** [seenthis/seenthis_squelettes#186]
Depuis environ 15h00 aujourd'hui (19/05) 

- lorsqu'on se logue sur seenthis
- quelle que soit l'action effectuée immédiatement après 
- (le moindre clic sur un lien) nous délogue.

**Comment by Fil** [comment]
le serveur est en cours de migration et l'ancien a été mis en lecture seule. On a juste oublié de prévenir :)

**Comment by biggrizzly** [comment]
On n'a pas oublié, le message de service existe : https://seenthis.net/messages/599816 
Mais... il n'est resté qu'une heure avant qu'on démarre :-)
