### ISSUE TITLE
Notification d'utilisateur bloqué 

### ISSUE THREAD

**Issue by pick-a-chu** [seenthis/seenthis_squelettes#188]
A bloque B
B créé un nouveau fil qui notifie A (@A)
A voit le nouveau fil dans la zone à côté des articles 

A priori ce n'est pas un comportement souhaitable

**Comment by brunob** [comment]
Bien vu, en fait ça n'est pas une notification (par email) et cela vient de ce squelette : 

https://github.com/seenthis/seenthis_squelettes/blob/master/alertes.html

Je corrige ça au plus vite.
