### ISSUE TITLE
améliorer l'embed d'archive.org

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#193]
https://seenthis.net/messages/640336

**Comment by brunob** [comment]
Ouep, comme je le disais dans ce commentaire https://github.com/seenthis/seenthis_squelettes/issues/122#issuecomment-275939718 c'est compliqué avec archive.org car ils envoient de la merde das les metas des pages => shit in, shit out cf https://zone.spip.org/trac/spip-zone/changeset/102562

**Comment by brunob** [comment]
Sur la page citée en exemple je vois bien un player qui permet d'écouter les 6 pistes audio (donc pas de bug en vue), mais oui, la vignette n'est pas présente et ça on doit pouvoir la choper depuis les metas, je vais tenter un truc à ce sujet.

**Comment by brunob** [comment]
Alors voilà, après pas mal de tests (archive.org envoyant du grand n'importe quoi comme infos à propos de ses embeds) je propose l'amélioration suivante uniquement pour les emebds audio : affichage de l'éventuelle image au dessus du player & hauteur du player fixé à 120 de manière arbitraire car c'est ce qui permet d'éviter un gros espace sous les players qui contiennent une playlist (reste une petite marge pour les player d'un son unique). Je ne peux pas mieux, car archive envoie la même info de largeur/hauteur dans les metas og/twitter que ça soit une playlist ou un audio unique.

Exemple en image : 

![Capture d’écran 2020-12-28 à 12 00 43](https://user-images.githubusercontent.com/418064/103209852-57670c00-4904-11eb-8e55-c6dec112159f.png)

Le diff prêt à être commité : 

```diff
diff --git a/autoembed.php b/autoembed.php
index b0070bf..a3440a5 100644
--- a/autoembed.php
+++ b/autoembed.php
@@ -196,6 +196,21 @@ function embed_url($url) {
 					$embed = "<a href='$url'><img src='$vignette' alt='' style='max-width:200px; max-height: 200px;' /></a>";
 				}
 
+				if ($source == "Archive.org") {
+					if ($page = @join("",file($url))) {
+						if (strpos($page, '<meta property="mediatype" content="audio">') 
+							and strpos($page, '<meta property="twitter:player" content="')
+						) {
+							if (preg_match(',<meta property="og:image" content="(.*)">,Uims', $page, $i1)) {
+								$img = $i1[1];
+								$embed = "<img src='$img' alt='' style='max-width: none; width: 99%; height: auto'/>";
+							}
+							$AE->setHeight('120');
+							$embed .= $AE->getEmbedCode();
+						}
+					}
+				}
+
 				// inserer une "class=oembed-source-mp3audio" 
 				$src = preg_replace(',[^\w]+,', '', strtolower($source));
```

**Comment by brunob** [comment]
Commité et up en prod

https://git.spip.net/spip-contrib-extensions/seenthis_autoembed/commit/0868f96ea52ae2639279597f022a1326504e4656
https://git.spip.net/spip-contrib-extensions/seenthis_autoembed/commit/276a8ca52bdbff83c91141c32cf87e876ffaacac

**Comment by martinarnaud** [comment]
Yes! Bravo, merci!

Arnaud
