### ISSUE TITLE
Modifier le flux RSS Twitter pour prendre en compte le passage à 280 caractères

### ISSUE THREAD

**Issue by thibnton** [seenthis/seenthis_squelettes#195]
Tout est dans le titre. 
Le flux en question : https://seenthis.net/people/thibnton/feed_tw
Avec mes remerciements à qui s'en saisira.

**Comment by Fil** [comment]
à priori ça se passe ici
https://github.com/seenthis/seenthis_squelettes/blob/c68482607386ab4c50a1d1874c00f9a4cad17dc0/noisettes/atom/atom_me_tw.html#L19

la fonction extraire_titre accepte un deuxième argument = longueur du titre (valeur par défaut = 100), donc on peut lui passer 240 (sachant qu'il faut laisser 36 pour l'URL).
cf. https://github.com/seenthis/seenthis/blob/d4d007a5b3512715b09b64ef1d5b851c7c8033a0/seenthis_options.php#L650

à tester

**Comment by brunob** [comment]
Et hop, patch proposé :)

**Comment by Fil** [comment]
avant/après
<img width="818" alt="capture d ecran 2017-12-11 a 20 08 51" src="https://user-images.githubusercontent.com/7001/33848900-5bc892e0-deaf-11e7-90e6-a1e4396bfa04.png">
![capture d ecran 2017-12-11 a 20 08 46](https://user-images.githubusercontent.com/7001/33848905-5c4f63ec-deaf-11e7-9e8c-e115378c88e7.png)

**Comment by thibnton** [comment]
Coolos, merci beaucoup.

**Comment by Fil** [comment]
hmmm c'est incomplet, car il aurait fallu aussi modifier le title
cf. https://twitter.com/recifs/status/943391120838594560

**Comment by thibnton** [comment]
Oui, moi je m'en étais sorti en modifiant dans ifttt pour ne garder que
{{{content}}}, j'aurais pu partager l'info, mais je voulais pas faire trop
iech non plus.

2017-12-20 9:55 GMT+01:00 Philippe Rivière <notifications@github.com>:

**Comment by Fil** [comment]
tu vois que c'est pas la bonne méthode
