### ISSUE TITLE
le flux rss n'est pas valide

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#20]
```
line 305, column 1: label should not contain HTML: &_Society; [help]
               <category term="Culture_&_Society" label="Culture_&_Society" scheme ...
```

cf. http://seenthis.net/messages/237395

**Comment by archiloque** [comment]
C'est quoi le soucis restant ?

**Comment by Fil** [comment]
justement, ce bout devrait aussi être échappé : `term="Culture_&amp;_Society"` ;  il s'agit des tags, ce que j'ai corrigé n'était que sur un titre

**Comment by archiloque** [comment]
Je n'arrive pas à trouver comment échapper les & dans les category pour que http://validator.w3.org/feed/ soit content, quel outil utilises-tu pour la validation ?

**Comment by Fil** [comment]
normalement ce serait `proteger_amp` ?

**Comment by archiloque** [comment]
Mon soucis n'est pas dans spip mais dans le xml: même à la main je n'arrive pas à trouver comment échapper le & pour que le validateur soit content, ni &amp; ni &#x26; ni rien que j'ai essayé

**Comment by Fil** [comment]
Ah ok ; vu qu'on va pas rajouter de DTD pour ça, on peut pas mettre
éventuellement ` &#38;` ?

-- Fil

**Comment by brunob** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fseenthis.net%2Fpeople%2F7h36%2Ffeed

Congratulations! This is a valid Atom 1.0 feed.

On est bons non ? On peut fermer ?

**Comment by brunob** [comment]
Toujours valide, on ferme :)
