### ISSUE TITLE
les mails de relance pour les flux pourraient être directement activables

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#200]
les mails envoyés au bout de 6 mois par https://github.com/seenthis/seenthis_importer_flux comportent une URL  "profil" `https://seenthis.net/index.php?page=profil`

On pourrait mettre à la place une URL "action" qui ferait : 
- suppression de l'étoile dans l'url du flux
- mise à jour de la date de connexion

**Comment by brunob** [comment]
On peut s'inspirer de ce qui est fait pour la modération des forums dans le plugin notifications, cf : 

https://zone.spip.org/trac/spip-zone/browser/_plugins_/notifications/trunk/action/instituer_forum_paremail.php#L12
https://zone.spip.org/trac/spip-zone/browser/_plugins_/notifications/trunk/notifications/forumposte.php#L68
https://zone.spip.org/trac/spip-zone/browser/_plugins_/notifications/trunk/notifications/forum_poste.html#L50

**Comment by brunob** [comment]
C'est en prod, on ferme :)
