### ISSUE TITLE
Quand on supprime ses commentaires d'un fil, on est toujours notifié

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#201]
Lorsqu'on a l'option activé, on reçoit des notifications dans les fils où on a discuté. Ok.

Maintenant si on s'est trompé, et qu'on *retire* notre commentaire, et bien le compte continue de faire partie de la liste des notifiés !

Quand on supprime un commentaire, il devrait y avoir une vérification pour savoir s'il reste au moins un commentaire de ce compte sur ce fil, ou bien s'il n'y en a plus du tout. Et s'il n'y en a plus, le compte devrait être supprimé des la liste des notifications (il y a une table en plus pour ça ? je ne sais pas comment ça marche)

**Comment by Fil** [comment]
cf. https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L221 il faudrait ajouter un `AND statut='publi'` ou quelque chose du genre

**Comment by Fil** [comment]
à tester

**Comment by brunob** [comment]
Fait par cf5458236f94b0ad980da046a3ced38a386b2c40
