### ISSUE TITLE
adresse expéditeur des notifications en dur

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#205]
Comme je le signalais sur IRC : 

```
je me suis fait eu par seenthis
sur octopouce on utilise facteur configuré comme il faut
sauf que...
https://github.com/seenthis/seenthis/blob/spip31/inc/seenthis_notifier.php#L74
les notifications de seenthis inscrivent en dur le mail de l'envoyeur
du coup, j'envoyais des mails depuis robot@octopouce.net
qui s'affichait horriblement comme : no-reply@www.octopouce.net
bouhou
```

https://github.com/seenthis/seenthis/blob/spip31/inc/seenthis_notifier.php#L74

Bug constaté sur octopouce.net qui est en 3.1, mais le problème est le même en 2.1.

Amha, le plus simple serait d'utiliser l'adresse email ~~du webmestre du site~~ d'envoi en tant qu'expéditeur des notifications, ainsi les utilisateurs peuvent la personnaliser et utiliser facteur branché sur un smtp externe sans problème. Je remarque que l'adresse no-reply est déjà en place sur https://seenthis.net/ecrire/?exec=config_contenu la modification n'aurait donc aucun impact.

Plan B, ajouter un énième define pour permettre de personnaliser cette adresse, un truc comme `define('_EMAIL_NOTIFICATIONS', 'no-reply@seenthis.net');`.

Vos avis ?

**Comment by cy-altern** [comment]
amha la solution la plus pratique (et la plus intuitive pour les habitués de SPIP) est celle d'utiliser l'adresse d'envoi des notifications (personnalisable via facteur donc)
