### ISSUE TITLE
entrées non supprimées dans spip_me_follow

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#208]
Je viens d'envoyer deux patchs (2aafc3109aa35c61566f177b0037692a0848765c & 6a28655b2695dbd504f45157b72326ec98a93690), dont je ne suis pas super satisfait, dans la branche 3.1 afin de corriger un bug dans le nombre de followers affichés sur la page d'un auteur.

On a un petit bug sympa : `SELECT id_follow FROM spip_me_follow f LEFT JOIN spip_auteurs a ON f.id_follow = a.id_auteur WHERE a.id_auteur IS NULL;` => **7775 rows**

En fouillant un peu plus, j'ai compris d'où vient le problème : 
- on ne supprime pas les entrées présentes dans la table `spip_me_follow` dans seenthis-cli lors de la suppression d'un compte ;
- on n'a pas de genie pour nettoyer cette table alors qu'on y insère automatiquement un id_auteur lors de l'inscription d'une personne depuis une page auteur cf https://github.com/seenthis/seenthis_squelettes/blob/spip31/seenthissq_pipelines.php#L8

Amha, il suffit d'ajouter un genie dans le plugin seenthis_squelettes pour supprimer les entrées en question dans la table `spip_me_follow`.

**Comment by brunob** [comment]
Corrigé dans la branche 3.1 :)

**Comment by rastapopougros** [comment]
Oui là c'est un cas où il faut clairement en génie de nettoyage régulier. :)

**Comment by brunob** [comment]
Pour revenir sur le patch initial, je pense qu'il faut tout de même le garder sans quoi on prend en compte dans le total les auteurs dont le statu est `nouveau` alors qu'on ne souhaite pas les afficher dans la boucle qui suit.
