### ISSUE TITLE
Créer une page de veille pour les comptes à spam

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#210]
@Fil disait :

> on devrait faire cette fameuse page qui affiche les comptes récents et pas connectés mais très productifs …

**Comment by brunob** [comment]
Autres critères possible pour les repérer :

* url_site = %pseudo%
* post de l'auteur contient l'url de son site

**Comment by brunob** [comment]
WIP dans la branche https://github.com/seenthis/seenthis_squelettes/tree/210

**Comment by brunob** [comment]
Démo visible ici : https://seenthis.net/spip.php?page=spam

Ça remonte déjà pas mal de spammers dans la colonne de droite, cool. Reste à fixer le bug de pagination de la double boucle du contenu central, qu'il faudrait remplacer par une boucle sur jointure. Et aussi chercher parmi les rédacteurs et visiteurs car sur octopoce les membres sont des rédacteurs (et non des visiteurs comme sur seenthis).

**Comment by brunob** [comment]
Wala, c'est corrigé, amha on peut déjà merger cette première version et la diffuser pour partager la veille au spam :)

**Comment by brunob** [comment]
PS : avant de merger, je propose de restreindre l'accès à cette page aux personnes identifiées, ça vous va ?

**Comment by brunob** [comment]
À force de virer du spam à la chaîne, je pense qu'on peut ajouter ces mots à la regex à spam : `wedding|manager|management`.

**Comment by brunob** [comment]
Autre idée repérée dans ce post de framablog https://framablog.org/2020/11/13/i-dont-want-any-spam/

> Nous avons désormais un script qui supprime automatiquement les comptes qui ne se sont jamais connectés dans les 10 jours suivant leur inscription : ce sont visiblement des comptes de spam qui ne reçoivent pas les mails de confirmation et donc ne se sont jamais connectés.

Ça pourrait être utile, avec un define qui permettrait de définir la durée en jours à partir de laquelle on supprime un nouveau compte qui ne s'est jamais connecté.

@seenthis/commiters votre avis ?

**Comment by rastapopougros** [comment]
oui avec un truc configurable ça me parait bien, mais du coup c'est une inscription normale de SPIP ? ce script (enfin génie)  ça pourrait alors être placé dans un plugin générique non ? (et du coup pas juste un define mais dans le panneau de config du plugin ?)

**Comment by brunob** [comment]
Huhu, je ne devais pas être réveillé ce jour là, ça existe déjà dans le core ce truc ^^

```
	# supprimer les auteurs 'nouveau' qui n'ont jamais donne suite
	# au mail de confirmation (45 jours pour repondre, ca devrait suffire)
```

https://git.spip.net/spip/spip/src/branch/master/ecrire/genie/optimiser.php#L202
