### ISSUE TITLE
&mdash; dans le titre des notifications

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#211]
Le mail de notification de https://seenthis.net/messages/791824 a pour sujet `Project Raven &mdash; Inside the UAE’s secret hacking team of American mercenaries`. Cela vient de `extraire_titre()` https://github.com/seenthis/seenthis/blob/spip31/seenthis_options.php#L671

```
$texte = 'Project Raven — Inside the UAE’s secret hacking team of American mercenaries';
var_dump(trim(extraire_titre(texte_de_me(726))));
=> Project Raven &mdash; Inside the UAE’s secret hacking team of American mercenaries
```

**Comment by brunob** [comment]
Plus précisément, cela vient de notre utilisation de `extraire_titre` dans https://github.com/seenthis/seenthis/blob/spip31/inc/seenthis_notifier.php#L176 ; en passant l'option `brut` à `true` ça fonctionne bien mieux => `trim(extraire_titre($texte, 100, true))`.

**Comment by brunob** [comment]
Corrigé, à voir s'il faudrait appliquer ça ici aussi https://github.com/seenthis/seenthis/blob/spip31/inc/seenthis_notifier.php#L345 mais j'en doute.

**Comment by brunob** [comment]
J'ouvre de nouveau car @Fil me dit que ça reste transcodé cf :

```
---------- Message transféré ---------
De : mad meg (mad_meg) - SeenThis <no-reply@seenthis.net>
Date : mer. 10 juil. 2019 à 07:11
Objet : Re : Du &laquo; transidentitaire &raquo; à l'enfant-machine :
entretien avec Fabien Ollier
```

Pourtant, je viens de tester sur mon instance locale avec le même titre et je ne reproduis pas :\

**Comment by brunob** [comment]
Avec le test suivant j'obtiens ceci https://seenthis.net/spip.php?page=bb

```
var_dump(extraire_titre(texte_de_me(791824)));
var_dump(extraire_titre(texte_de_me(791824), 100, true));

var_dump(extraire_titre(texte_de_me(791830)));
var_dump(extraire_titre(texte_de_me(791830), 100, true));
```

Donc si c'est encore transcodé, ça doit venir de facteur, mais je l'utilise aussi sur mon instance de test...

**Comment by brunob** [comment]
Ha, je crois que j'ai trouvé le fautif !

https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/typo_guillemets/typo_guillemets_fonctions.php#L31

https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/typo_guillemets/plugin.xml#L18

Comme facteur génère des mails html, typo guillemets entre en action dans ce squelette :+1: 

https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/emails/texte.html

On pourrait rétablir les mails texte uniquement en suivant l'astuce donnée dans le commentaire : 

```
// si le mail est en texte brut, on l'encapsule dans un modele surchargeable
// pour garder le texte brut, il suffit de faire un modele qui renvoie uniquement #ENV*{texte}
```
https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/inc/envoyer_mail.php#L115

**Comment by brunob** [comment]
```
< b_b‎ >  haha le sketche
< b_b‎ >  forcément
< b_b‎ >  https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/inc/envoyer_mail.php#L117
< b_b‎ >  si pas de messge html => créer un message html
< b_b‎ >  et si message html => content type html
< b_b‎ >  https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/classes/facteur.php#L185
< b_b‎ >  donc on ne peut pas faire uniquement des mails txt avec facteur
```

Ça vient de ce commit https://zone.spip.net/trac/spip-zone/changeset/59363/spip-zone

**Comment by brunob** [comment]
Avec le retour des mails de notifications au format texte brut on devrait être bons (j'espère), je ferme le ticket.

**Comment by brunob** [comment]
Et c'est reparti... reçu à l'instant `Mère de famille fauchée à Montpellier : &laquo; La catastrophe est arrivée ! &raquo;` cf https://seenthis.net/messages/792830

Si quelqu'un est intéressé pour y regarder de plus prêt, de mon côté j'ai juste envie de désactiver le plugin guillemets typographiques /me blasé

**Comment by brunob** [comment]
Comme je ne lâche pas l'affaire comme ça, j'y ai passé encore "un peu" de temps, et je découvre que c'est `nettoyer_titre_email()` qui effectue cette transformation cf 

```
$texte = 'Mère de famille fauchée à #Montpellier : "La catastrophe est arrivée !"';
var_dump(trim(extraire_titre($texte, 100, true))); => 'Mère de famille fauchée à Montpellier : "La catastrophe est arrivée !"'
var_dump(nettoyer_titre_email(trim(extraire_titre($texte, 100, true)))); => 'Mère de famille fauchée à Montpellier : &laquo; La catastrophe est arrivée ! &raquo;'
```

**Comment by rastapopougros** [comment]
Et donc tout simplement parce que nettoyer_titre_email() utilise corriger_typo() qui est le cœur de typo() et c'est là qu'il y a les pipelines pre_typo et post_typo, donc que le plugin Orthotypo ou assimilé fait son œuvre.

**Comment by rastapopougros** [comment]
Plutôt que de forcer un autre titre, alors que ce qui a été fait avant peu contenir des choses intéressantes, y compris de correction typo indispensable (espaces, etc), est-ce qu'on ne peut pas simplement prendre ce qui a été produit et passer dessus une fonction qui remet les entités en vrais caractères UTF ?

**Comment by brunob** [comment]
Pour comparaison, en 2.1 on n'utilisait pas facteur et donc on utilisait `envoyer_mail()` du core qui n'appliquait que `nettoyer_caracteres_mail()` au sujet : 

https://core.spip.net/projects/spip/repository/entry/branches/spip-2.1/ecrire/inc/envoyer_mail.php#L161

Fonction qui avait "le bon goût" de remplacer les `&mdash;` par `--` cf https://core.spip.net/projects/spip/repository/entry/branches/spip-2.1/ecrire/inc/envoyer_mail.php#L87

D'ailleurs si je reprends l'exemple précédent, on obtient `var_dump(nettoyer_caracteres_mail(trim(extraire_titre($texte, 100, true)))); => 'Mère de famille fauchée à Montpellier : "La catastrophe est arrivée !"'` qui est bien ce qu'on "souhaite" :)

**Comment by brunob** [comment]
@rastapopougros quand tu dis : 

> est-ce qu'on ne peut pas simplement prendre ce qui a été produit et passer dessus une fonction qui remet les entités en vrais caractères UTF ?

Je doute sur le fait d'appeler une fonction pour défaire ce qui a été fait plus haut. À quelle fonction penses-tu ?

**Comment by rastapopougros** [comment]
@brunob bé : 
`var_dump(html_entity_decode('Mère de famille fauchée à Montpellier : &laquo; La catastrophe est arrivée ! &raquo;'));`
string(78) "Mère de famille fauchée à Montpellier : « La catastrophe est arrivée ! »"

**Comment by brunob** [comment]
Dans ce cas on pourrait utiliser la méthode `html2text` de la classe phpmailer https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/phpmailer-php5/class.phpmailer.php#L3494

Ou celle proposée par la classe facteur, mais celle-ci semble bien plus complexe https://zone.spip.net/trac/spip-zone/browser/spip-zone/_plugins_/facteur/trunk/facteur_fonctions.php#L307 et elle renvoie du markdown.

Sinon, un simple `html_entity_decode` comme tu le proposes + les bonnes options devrait faire l'affaire.

**Comment by rastapopougros** [comment]
Normalement, à l'endroit dont on parle, il n'y a jamais de HTML, de balises, donc html2text ou l'autre c'est pas pour ça. Là on parle juste d'entités uniquement, à priori.

**Comment by brunob** [comment]
Je parlais de cette méthode car elle appelle justement `html_entity_decode` et rien d'autre :p

**Comment by brunob** [comment]
Proposition de patch : 

```diff
diff --git a/seenthis_pipelines.php b/seenthis_pipelines.php
index 6277467..e956343 100644
--- a/seenthis_pipelines.php
+++ b/seenthis_pipelines.php
@@ -21,5 +21,7 @@ function seenthis_facteur_pre_envoi($facteur){
 	// focer les mails au format txt
 	$facteur->ContentType = 'text/plain';
 	$facteur->AltBody = '';
+	// décoder les entités html du sujet (insérées par typo_guillemets dans post_typo par exemple)
+	$facteur->Subject = html_entity_decode($facteur->Subject, ENT_QUOTES, $facteur->CharSet);
 	return $facteur;
 }
```

**Comment by rastapopougros** [comment]
On peut déjà faire ça, et puis si on voit d'autres problèmes arriver on complètera.

**Comment by brunob** [comment]
Patch commité, up en prod, je ferme et on y reviendra si nécessaire.
