### ISSUE TITLE
Surcharge lorsque copie_locale est rejetée par le serveur distant

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#214]
Contexte : le post suivant https://seenthis.net/messages/792332 contient plus de 10 images provenant du même site, mais le site en question bloque l'accès à ses images depuis le serveur de seenthis cf : 

```
biggrizzly@seenthis:~$ wget http://www.kedistan.net/wp-content/uploads/2018/03/DSC04005-photo-loez-lavrio.jpg
--2019-07-12 14:57:59--  http://www.kedistan.net/wp-content/uploads/2018/03/DSC04005-photo-loez-lavrio.jpg
Resolving www.kedistan.net (www.kedistan.net)... 109.234.161.61
Connecting to www.kedistan.net (www.kedistan.net)|109.234.161.61|:80... 
```

Pendant toute la période où ce post était affiché en page d'accueil, cela a entraîné une surcharge du serveur à cause de plein de scripts php-fpm bloqués sur l'action `creer_miniature()` https://github.com/seenthis/seenthis_squelettes/blob/spip32/action/creer_miniature.php

```
/spip.php?action=creer_miniature&id_auteur=1&img=http%3A%2F%2Fwww.kedistan.net%2Fwp-content%2Fuploads%2F2018%2F03%2FDSC04854-photo-loez-lavrio.jpg&maxw=600&maxh=700&sec=dddaae8f 
```

On pourrait peut-être jouer avec `_INC_DISTANT_CONNECT_TIMEOUT` pour atténuer ça ?

https://core.spip.net/projects/spip/repository/entry/spip/ecrire/inc/distant.php#L34

**Comment by brunob** [comment]
Je viens de regarder ce qui se passe avec `afficher_miniature()` qui est la source du problème. Cette fonction lance une `copie_locale` en mode `test` et si ça passe elle appelle `calculer_miniature()`, si ça échoue elle appelle l'action `creer_miniature` qui elle aussi appelle `calculer_miniature()`.

Ce qui m'étonne, c'est que dans l'action `creer_miniature` on tente de faire une `copie_locale` de l'image avant d'appeler `calculer_miniature()` alors que celle-ci fait aussi un appel à `copie_locale`, c'est donc double peine quand le serveur en face refuse le hotlinking et renvoie une page 404 (qui au final se retrouve copiée dans `IMG/disntant` avec un contenu html dans le fichier).

Amha, il faudrait d'abord lancer et tester le résultat de `copie_locale` dans l'action avant d'appeler `creer_miniature()` cela permettrait déjà d'optimiser l'action, cf le diff suivant qui comporte aussi un peu de remise en forme du code : 

``` diff
diff --git a/action/creer_miniature.php b/action/creer_miniature.php
index 5e9a848..867866a 100644
--- a/action/creer_miniature.php
+++ b/action/creer_miniature.php
@@ -3,30 +3,22 @@
 function action_creer_miniature_dist() {
 	include_spip('inc/acces');
 	include_spip('inc/filtres');
-	if ($img = _request('img')
-	AND $maxw = _request('maxw')
-	AND $maxh = _request('maxh')
-	AND $sec = _request('sec')
-	AND verifier_low_sec(1, $sec, "miniature $maxw $maxh $img")) {
+	if ($img = _request('img') and $maxw = _request('maxw') and $maxh = _request('maxh') and $sec = _request('sec') and verifier_low_sec(1, $sec, "miniature $maxw $maxh $img")) {
 		include_spip('seenthis_fonctions');
 		include_spip('inc/distant');
 		spip_log('debut copie locale '.$img, 'distant');
-		if (copie_locale_safe($img)
-		AND $image = calculer_miniature($img, $maxw, $maxh)
-		AND $miniature = extraire_balise($image,'img')) {
-			spip_log('fin copie locale '.$img, 'distant');
-			echo $image;
-			exit;
-		}
-
-		# si l'image n'existe pas (ou n'est pas accessible)
-		else
+		if (copie_locale_safe($img)) {
+			if ($image = calculer_miniature($img, $maxw, $maxh) and $miniature = extraire_balise($image,'img')) {
+				spip_log('fin copie locale '.$img, 'distant');
+				echo $image;
+				exit;
+			}
+		} else { # si l'image n'existe pas (ou n'est pas accessible)
 			spip_log('echec copie locale '.$img, 'distant');
-	}
-	# si le code de securite n'est pas bon
-	else
+		}
+	} else { # si le code de securite n'est pas bon
 		spip_log('acces interdit', 'distant');
-
+	}
 	echo inserer_attribut('<img />', 'src', find_in_path('imgs/verif_no.png'));
 	exit;
 }
```

Toujours dans cette action, on pourrait faire une `copie_locale` en mode `test` pour gagner du temps, sauf que, si je fais ça, j'obtiens bien la miniature mais je n'ai plus de copie de l'image originale dans `IMG/distant` :\

Bref, tout ceci pourrait être amélioré :)

**Comment by brunob** [comment]
Un simple test comme `var_dump(afficher_miniature('http://www.kedistan.net/wp-content/uploads/2018/03/DSC04005-photo-loez-lavrio.jpg', 600, 700));` me montre qu'on passe trois fois dans `copie_locale()` en mode test et une autre fois en mode `auto`...

**Comment by rastapopougros** [comment]
Je ne pige pas ce que fais le diff, c'est très bien les "and" dans le même "if" (et un test suivant ne se lance pas si le précédent n'est pas true déjà), ya pas besoin d'imbriquer des if à priori.

copie_locale() ça vaut pour n'importe quelle ressource, donc même si une URL retourne du HTML (car une 404 par ex alors qu'on demandait un jpg) ça va le télécharger quand même. Or là on veut spécifiquement traiter que des images, puisqu'on veut faire des miniatures. Est-ce qu'on ne peut pas d'abord tester si 1) ça répond bien + 2) c'est bien un mime type d'image *avant* de demander une copie locale et lancer une miniature ? Mais ça augmenterait le nombre de requête HTTP à priori.

**Comment by brunob** [comment]
@biggrizzly disait :

> Juste pour parler de ma partie : avec les firewalls, soit on REJECT, et là, le tiers se retrouve tout de suite au courant qu’il n’est pas bienvenu, soit on DROP, et là, le tiers se retrouve sur une erreur réseau bas niveau, avec un time-out qui peut être très long… Quand on veut être méchant, on DROP.
Ils sont méchants avec les gens qui veulent afficher leurs images sur leurs sites sans les autoriser explicitement… J’imagine que le SPIP devrait ajouter un referer pertinent pour ne pas être viré automatiquement et peu sympathiquement de la sorte. J’imagine.

De mon côté, j'ai tenté de fourber le user agent avec `define('_INC_DISTANT_USER_AGENT', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0');` sans obtenir de meilleur résultat.

> Pour le « pourquoi ». Chaque visiteur de seenthis déclenche le téléchargement de l’image. Tant qu’elle n’est pas en vignette, le programme va tenter de… et une solution pourrait être de déléguer ce vignettage à un message queue pour que lui ne tente pas de le réaliser des milliers de fois, et que SPIP ne se retrouve pas bloqué à tenter de générer la vignette au sein de 50 processus php-fpm. Notez qu’il y a une instance de memcached. On pourrait implémenter un lock avec expiration avec l’identifiant de l’image, pour éviter de lancer plus d’une tentative de vignettage.

Ouep, c'est bonne une piste d'évolution de ce vieux code...

**Comment by biggrizzly** [comment]
Le "fourbage" arrive trop tard pour cette image particulière à mon avis. J'imagine un blocage du firewall qui s'active quand des images ont été réclamées un grand nombre de fois. Mais en général, ce "fourbage" pourra être plus mieux. 

Le plus important est qu'il ne faut pas réclamer 100 fois la même image dans un délai très court. Il faut peut-être se donner une chance de retenter le téléchargement plus tard... Tiens, si le verrouillage par memcache a une expiration d'une heure, une image non-téléchargée ne sera téléchargée à nouveau qu'une heure plus tard.

**Comment by brunob** [comment]
> Le "fourbage" arrive trop tard pour cette image particulière à mon avis. J'imagine un blocage du firewall qui s'active quand des images ont été réclamées un grand nombre de fois. Mais en général, ce "fourbage" pourra être plus mieux.

@biggrizzly si tu parles bien du user agent, je peux déjà ajouté ça au mes_options du site, ça ne mange pas de pain.

Pour l'évolution du système de gestion de miniatures, je regarde ça asap, mais rien n'empêche les autres @seenthis/commiters de s'y pencher :)

**Comment by biggrizzly** [comment]
Je parle de renseigner l'entête Referer, pour que le serveur http puisse constater que la demande est issue d'un site conforme (celui du Washington Post en l'occurrence pour le cas qui nous a occupé ce jour).

Pour la gestion des miniatures, ce sera proprement génial quand tu le feras. Mais entre nous, c'est tout de même rare qu'on se prenne des difficultés comme celle-là et ce n'est donc pas hyper urgent. Mais c'est vrai qu'y passer du temps comme aujourd'hui, j'aurais pu faire autre chose plutôt que de faire ce diagnostic compliqué. :-))

**Comment by brunob** [comment]
> Je parle de renseigner l'entête Referer, pour que le serveur http puisse constater que la demande est issue d'un site conforme (celui du Washington Post en l'occurrence pour le cas qui nous a occupé ce jour).

J'ai tenté en local ça en forçant le header depuis `recuperer_url')` mais la requête était toujours bloquée.

> Pour la gestion des miniatures, ce sera proprement génial quand tu le feras. Mais entre nous, c'est tout de même rare qu'on se prenne des difficultés comme celle-là et ce n'est donc pas hyper urgent. Mais c'est vrai qu'y passer du temps comme aujourd'hui, j'aurais pu faire autre chose plutôt que de faire ce diagnostic compliqué. :-))

Claro, c'est bien pour nous éviter de passer du temps là dessus à l'avenir qu'il faut s'y coller "plus ou moins rapidement" ^^

**Comment by biggrizzly** [comment]
Comme je l'indiquais, la requête était tjs bloquée, parce que l'IP du serveur avait été bloquée par le firewall :
- Protection niveau 1 : je ne sers pas une image avec un mauvais referer, et je décompte ces tentatives 
- Protection niveau 2 : cette IP a dépassé les limites, je bloque par le firewall
Tu peux programmer ce genre de protection avec fail2ban par exemple.
C'est pour cela que pour l'avenir, il faut à mon sens toujours mettre le bon referer.

**Comment by Fil** [comment]
désolé je ne sais pas très bien quoi faire pour aider—on a ce problème depuis le début de seenthis, il m'est arrivé plusieurs fois d'aller bloquer des sites méchants à la main dans le /etc/hosts 

(php ne permettant pas les requêtes asynchrones, on aura toujours un cas pourri où le truc se bloque)

sinon il faut essayer d'installer un proxy du genre https://docs.imgproxy.net/ dans un endroit secret, et composer la requête qui va bien (pas la peine de se fatiguer à la signer si l'url du serveur est secrète)

**Comment by brunob** [comment]
@Fil je te pingais sur cette proposition de @biggrizzly 

> Notez qu’il y a une instance de memcached. On pourrait implémenter un lock avec expiration avec l’identifiant de l’image, pour éviter de lancer plus d’une tentative de vignettage.

On pourrait peut-être ajouter ça en quelques lignes dans l'action qui pose problème, afin qu'elle ne soit pas lancée X fois alors qu'une seule suffit, surtout quand elle est vouée à l'échec.

> sinon il faut essayer d'installer un proxy du genre https://docs.imgproxy.net/ dans un endroit secret, et composer la requête qui va bien (pas la peine de se fatiguer à la signer si l'url du serveur est secrète)

Super, merci pour le lien, j'y pensais justement cet am et je ne retrouvais pas le nom du bouzin, c'est peut-être bien la piste à suivre, ainsi on délègue cette partie à un truc externe dont c'est le job (en prenant le risque d'augmenter le stack et donc le travail de maintenance, mais ça peur valoir le coup). De plus, si on tente ça, on peut rendre le truc optionnel avec un simple define, afin que seenthis de base ne nécessite pas impérativement ce proxy.

**Comment by Fil** [comment]
> implémenter un lock

c'est une bonne idée pour empêcher de bloquer le serveur, mais ça n'empêchera pas d'être bloqués et de traîner le chargement de cette image (?)

**Comment by biggrizzly** [comment]
memcache peut aussi être utilisé pour stocker le nombre d'essais pour une image particulière, et si ce nombre d'essai est trop élevé, on peut stocker dans la table de base de données que cette image ne doit plus être récupérée définitivement. Et rien que le lock permettra de ne mobiliser qu'un slot php-fpm au lieu de plusieurs dizaines, c'est déjà énorme en terme de sécurisation du processus.
Ça me paraît moins contraignant que d'ajouter un logiciel de plus à maintenir en tout cas. Mais c'est vous les sachants pour ce code source... Je ne maîtrise pas les contraintes liées à cette fonctionnalité.

**Comment by brunob** [comment]
>  Ça me paraît moins contraignant que d'ajouter un logiciel de plus à maintenir en tout cas. 

Je partage un peu cet avis aussi, d'où ma remarque entre parenthèses ;)

> Mais c'est vous les sachants pour ce code source... Je ne maîtrise pas les contraintes liées à cette fonctionnalité.

Sachez très cher que je ne sais pas grand chose :p 

Plus sérieusement, si on peut éviter de flooder le serveur avec un petit patch à l'existant, ça me va très bien.

**Comment by brunob** [comment]
Est-ce que ce simple patch ne ferait pas le job ?

```diff
diff --git a/action/creer_miniature.php b/action/creer_miniature.php
index 5e9a848..ee2ddc0 100644
--- a/action/creer_miniature.php
+++ b/action/creer_miniature.php
@@ -8,13 +8,17 @@ function action_creer_miniature_dist() {
 	AND $maxh = _request('maxh')
 	AND $sec = _request('sec')
 	AND verifier_low_sec(1, $sec, "miniature $maxw $maxh $img")) {
+		// poser un lock memoization pour ne pas lancer de générations concurrentes de l'image
+		cache_set($img, 1);
 		include_spip('seenthis_fonctions');
 		include_spip('inc/distant');
 		spip_log('debut copie locale '.$img, 'distant');
-		if (copie_locale_safe($img)
+		if (!cache_exists($img)
+		AND copie_locale_safe($img)
 		AND $image = calculer_miniature($img, $maxw, $maxh)
 		AND $miniature = extraire_balise($image,'img')) {
 			spip_log('fin copie locale '.$img, 'distant');
+			cache_del($img);
 			echo $image;
 			exit;
 		}
```

**Comment by brunob** [comment]
Je teste le patch en question et ça n'est pas encore assez car lors de l'appel de `afficher_miniature()` https://github.com/seenthis/seenthis_squelettes/blob/master/seenthissq_fonctions.php#L230 on lance :+1: 
- `copie_locale()` en mode test 
- qui déclenche `fichier_copie_locale()` 
- qui tente de récupérer des infos sur le fichier distant cf https://git.spip.net/spip/spip/src/branch/3.2/ecrire/inc/distant.php#L1044

Et paf...

**Comment by brunob** [comment]
Je pense que le fix proposé dans #273 est le bon, ainsi on règle le problème à la source, c'est à dire dans `copie_locale_safe()`, fonction par laquelle tout passe dans ce cas.

J'ai testé en affichant un poste avec l'image qui bloque + une autre qui ne bloque pas. Lors du premier hit, ça mouline et ça finira en timeout comme avant, par contre l'affichage dans un autre hit affiche bien le message direct avec la tite croix rouge habituelle en cas d'échec pour l'image qui bloque, et l'image non bloquante et bien affichée.

**Comment by biggrizzly** [comment]
Clap Clap :-)

**Comment by brunob** [comment]
@seenthis/commiters on envoie en prod et on voit si ça pète ? Sinon, vous pouvez aussi relire le micro patch, ça ne demande pas trop de temps :)

**Comment by rastapopougros** [comment]
j'y connais rien en memcache et ces fonctions cache_truc, donc je ne suis pas capable de dire ce que ça va faire ou pas, si c'est bien ou pas. Mais bon j'ai compris l'idée, et go go si c'est bon, ça pourrait pas trop plus péter qu'avant la modif :)

**Comment by biggrizzly** [comment]
cache_exists, je n'ai pas le code source, on trouve sa déclaration où ? Habituellement, on aime mettre en cache avec une durée, et avec un préfixe, pour ne pas avoir de collisions avec différents besoins de mise en cache (préfixe) et afin que la mise en cache soit limitée (durée).

**Comment by brunob** [comment]
@biggrizzly le code de ces fonctions est ici https://git.spip.net/spip-contrib-extensions/memoization/src/branch/v2/memoization_options.php

Au début j'avais préfixé les entrées de cache par le mode en plus de l'url de la source à récupérer, mais comme c'est la seule utilisation de ce type dans seenthis, je me suis dit qu'il ne devrait pas y avoir de risque de collision. Pour la durée, j'ai préféré ne pas en fixer afin de ne pas "permettre au bug de refaire surface" XXh après le premier hit, et puis c'est du memcached sur seenthis, donc volatile. Si vous pensez qu'il est plus approprié de coller une durée, dites le moi et filez moi une valeur et j'ajoute ça :)

**Comment by brunob** [comment]
Pour revenir sur la question de l'éventuel ttl à appliquer à cette valeur de cache, à ce jour on a un max execution time de 30s sur seenthis, mais je ne pense pas que ça vaille le coup de relancer un process PHP toutes les minutes sur une récupération de contenu vers un serveur qui nous bloque. Disons qu'on pourrait se le permettre toutes les 24h peut-être ? Le danger, est que cela permettrait à un bot d'indexation qui passe sur le site de relancer X process de ce type d'un coup.

Bref, je pense qu'on peut envoyer tel quel, et on affinera si on remarque ça bloque des récupérations de contenu par erreur. Ça vous va ?

**Comment by brunob** [comment]
Et hop, c'est en prod :)

**Comment by biggrizzly** [comment]
Bravo et merci. Pour ma part, pas d'anomalie à signaler.
