### ISSUE TITLE
Langue de l'interface

### ISSUE THREAD

**Issue by khodr** [seenthis/seenthis_squelettes#215]
Quand je choisi une langue autre que le français dans les préférences il n’y a que la page des préférences qui prend cette langue toutes les autres pages restent en français.

**Comment by brunob** [comment]
Salut, je ne reproduis pas le bug, si je choisis l'anglais comme langue dans mes préférences, je vois bien l'explication à propos de la bookmarklet en anglais sur la page d'accueil cf `How to use: when you visit the web page of an article you wish to reference, select the text abstract you want to quote, and click on the bookmarklet.`. Ton navigateur accepte bien les cookies ?

**Comment by khodr** [comment]
Hello, ça doit être une histoire de cache car aujourd'hui, l'interface est en anglais.

**Comment by brunob** [comment]
Super, merci pour le retour :)
