### ISSUE TITLE
Posts doublons depuis flux mediapart

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#216]
Ça fait plusieurs fois que je remarque ça en parcourant /all à la recherche de comptes à spam, tous les posts de mediapart sont en doublon, exemple :

https://seenthis.net/messages/792985
https://seenthis.net/messages/792993

L'url contenue dans chaque post est un peu différente :

https://www.mediapart.fr/journal/france/160719/parafoudres-et-vague-de-cancers-orange-vise-par-une-une-plainte
https://www.mediapart.fr/journal/france/160719/parafoudres-et-vague-de-cancers-orange-vise-par-une-plainte

Ainsi que les tags associés aux posts.

Autre exemple :

https://seenthis.net/messages/792415
https://seenthis.net/messages/792396

Est-ce qu'on peut faire quelque chose pour éviter ça dans le plugin seenthis_importer_flux ou est-ce qu'on considère que ça n'est pas bien important ?

**Comment by brunob** [comment]
On dirait bien que ça concerne aussi le flux de cuisine libre, cf https://seenthis.net/people/cuisinelibre : 

https://seenthis.net/messages/801838
https://seenthis.net/messages/801943

https://seenthis.net/messages/801895
https://seenthis.net/messages/801935

**Comment by Fil** [comment]
on doit pouvoir unifier quand la différence est http / https, mais pas pour le cas d'une URL corrigée

**Comment by brunob** [comment]
Pour info, cuisine libre indique un flux en http alors que l'url du site SPIP en question est en https et le liste est accessible aussi bien en http que https (au lieu de forcer une redirection du premier vers le second). On est pas aidés sur ce coup là, mais soyons sympas tentons de prendre en charge ce genre de bourdes de notre côté :p

**Comment by brunob** [comment]
Peut-être en lien avec #130
