### ISSUE TITLE
[URGENT] L'API ne fonctionne plus (tous les seens sont perdus) 

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/seenthis_squelettes#218]
Depuis le 12 juillet, l'API perd les seens. Elle renvoie bien 200 mais les seens n'apparaissent nulle part.
Le dernier que j'ai envoyé était le 28 juillet à 15:47:25.

(Déjà signalé https://github.com/seenthis/hebergement/issues/25 mais il parait qu'il faut le faire ici.)

**Comment by brunob** [comment]
Je crois avoir trouvé la cause du bug, cf :

> Avertissement : Cette fonctionnalité est OBSOLÈTE à partir de PHP 5.6.0 et a été SUPPRIMÉE à partir de PHP 7.0.0. 

https://www.php.net/manual/fr/reserved.variables.httprawpostdata.php

J'envoie un patch tout de suite...

**Comment by brunob** [comment]
Appliqué et poussé en prod, ça devrait être bon maintenant @bortzmeyer ;)

**Comment by bortzmeyer** [comment]
Ça marche, les messages arrivent.
