### ISSUE TITLE
supprimer les scripts spécifiques à ie9

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#226]
Pour continuer dans le ménage lancé par #225, on pourrait peut-être se passer de ces scripts spécifiques à un navigateur dont le support est terminé cf https://support.microsoft.com/fr-fr/help/17454/lifecycle-faq-internet-explorer

Il suffit de supprimer leur répertoire https://github.com/seenthis/seenthis_squelettes/tree/master/javascript/ie9 et leurs appels https://github.com/seenthis/seenthis_squelettes/blob/master/inc/head.html#L26

Votre avis ?

**Comment by rastapopougros** [comment]
+1 
coder pour les navs qui font plus de 1% d'utilisation

**Comment by brunob** [comment]
grml, désolé pour le bruit ma branche master locale ne devait pas être propre...
