### ISSUE TITLE
Bug de gestion de la touche Entrée pendant la rédaction

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#229]
Parfois la touche Entrée seule valide le message même sans ajouter Maj ou Ctrl.

Le bug est dû à la mauvaise gestion de Ctrl.

Maj + Entrée = ça envoie
Ctrl + Entrée = ça envoie aussi

Maj seule PUIS Entrée seule = ça envoie pas et ça passe à la ligne
Ctrl seule PUIS entrée seule = ça envoie !

Donc il suffit d'avoir appuyer sur Ctrl pour tout autre chose avant, et hop à la prochaine touche Entrée ça va envoyer. Alors que ça devrait le faire que quand il y a vraiment les deux à la fois.

**Comment by Fil** [comment]
https://github.com/seenthis/seenthis_squelettes/blob/master/javascript/seenthis/seenthis.js#L294

il y a bien un `isShift = false;` mais pas de `isCtrl = false;` qui viendrait annuler le truc quand on lâche la touche.

**Comment by brunob** [comment]
Patch proposé, ça marche chez moi ©, il n'attend plus que vos +1 pour passer en prod.

**Comment by Fil** [comment]
validé et mis en prod… au passage suprise: #232
