### ISSUE TITLE
cache_url_fil() explose mysql quand on lui passe 0 comme paramètre

### ISSUE THREAD

**Issue by jmoupah** [seenthis/seenthis_squelettes#230]
Sur ce post https://seenthis.net/messages/805016

Lorsque je le modifie, quand je valide, ça reste bloqué sur le rechargement ajax et ma modification n'est pas prise en compte (donc je ne peux pas le modifier).

Lorsque je commente, ça reste aussi bloqué sur le rechargement ajax, mais le commentaire est bien pris en compte si je recharge la page (F5).

Je ne reçois pas les notifications de nouveaux commentaires alors que je les reçois bien sur d'autres fils.

Tests effectués sur ordi et tablette.

Rasta confirme le problème.

**Comment by Fil** [comment]
Si on est patient dans la console on voit un gateway timeout (après 2 minutes) ; il est possible que sur ce thread, seenthis cherche à charger une URL qui ne répond pas ? C'est une hypothèse.

**Comment by brunob** [comment]
Je vois ça passer dans les logs : 

```
 PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/stdev.zoo-logique.org/public_html/plugins/memoization/trunk/memo/memcache.inc on line 54
```

Je pensais à un problème avec une url oembed, mais ça ne semble pas venir de là, j'en ai tout de même profité pour passer le endpoint de soundcloud en https car on avait plein d'erreurs de ce type dans les logs : 

```
PHP Warning:  file(http://soundcloud.com/oembed?format=json&amp;url=https://soundcloud.com/user-898678423/instants-choisis-et-si-on-essayait-quelque-chose-frederic-lordon): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

**Comment by brunob** [comment]
@jmoupah tu rencontres toujours le problème à ce jour (sur ce post ou un autre) ?

**Comment by jmoupah** [comment]
@brunob oui, pareil sur ce post. Mais maintenant, au bout de 10 ou 20s, le rechargement ajax s'arrête j'ai un message d'erreur : 
![Screenshot_2020-11-21  Habibi Funk, le label qui joue à cache-cache dans la…](https://user-images.githubusercontent.com/18148022/99874455-6e6d5c80-2be8-11eb-8f4e-bd358e4fbff0.png)

**Comment by brunob** [comment]
De mon côté, tout ce que je vois dans les logs qui semble correspondre c'est ceci : 

```
[21-Nov-2020 10:54:26 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/stdev.zoo-logique.org/public_html/plugins/memoization/memo/memcache.inc on line 54
[21-Nov-2020 10:54:34 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/stdev.zoo-logique.org/public_html/ecrire/req/mysql.php on line 463
[21-Nov-2020 10:56:02 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/stdev.zoo-logique.org/public_html/plugins/memoization/memo/memcache.inc on line 54
```

Et @Fil semble avoir la bonne piste car l'image référencée dans le premier post du thread est en 404 à ce jour cf https://pan-african-music.com/wp-content/uploads/2019/09/Habibi-Funk-Jannis-Stu%CC%88rtz-8.jpg mais aucune trace de cette url dans les logs d'erreur...

**Comment by brunob** [comment]
Et si j'active les logs verbeux de SPIP, je vois ça passer cache.log : 

```
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_message(887767, 0)
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_mot_fil(805016)
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_url_fil(0)
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_url (0)
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_url_fil(1)
2020-11-22 19:16:20 77.196.191.186 (pid 31035) :Pub:info: cache_url (1)
```

La ligne `cache_url_fil(0)` va lancer un `sql_select("id_syndic", "spip_syndic", "id_parent=0);` qui me semble être le bon candidat pour le time out :p

**Comment by brunob** [comment]
Tant qu'à y être, j'ai vérifié qu'on avait pas d'autres cas similaire en base : 

```
select count(*) from spip_me_syndic where id_syndic=0;
+----------+
| count(*) |
+----------+
|     1599 |
+----------+
1 row in set (0.00 sec)
```

Amha il faut supprimer toutes ces entrées, vos avis ?

**Comment by brunob** [comment]
done
