### ISSUE TITLE
Quand on bloque une personne, ne plus pouvoir être suivi par elle

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#233]
Aude en a parlé plusieurs fois. Seenthis est certe public, mais il y a des choses qui sont plus ou moins facile à faire. Quand on n'est pas inscrit, anonyme, on ne peut pas suivre facilement le moindre écrit d'une personne (tous ses commentaires).

Quand on bloque explicitement un compte, il faudrait interdire que celui-ci puisse nous suivre, recevoir des notifications dès qu'on dit un truc, que ce soit nouveau seen ou commentaire, histoire de pas promouvoir un comportement malsain. Ces contenus sont bien sûr toujours visible par la personne mais il y a une différence entre l'avoir accessible et être prévenu de tout par des notifs.

Donc concrètement au niveau technique je vois deux possibilités :
- soit quand on bloque une personne, il faudrait désactiver ses abonnements à la personne qui a bloqué
- soit dans les différents traitements, il faut exclure les personnes qui nous on bloqué (quand on fait la liste des notifs à envoyer, faut enlever les seens et commentaires des gens qui nous ont bloqué)

**Comment by brunob** [comment]
La première option me semble plus propre et éco car elle éviterait d'avoir des conditions en plus dans le traitements des notifications. Par contre, elle supprime une info et ne permet pas de revenir en arrière. Ainsi, la personne qui me suivait avant bloquage devrait de nouveau demander à me suivre si je la débloque (mais ça ne me semble pas si problématique que ça).

**Comment by rastapopougros** [comment]
Oui c'est pour ça que j'ai aussi mis la deuxième manière. Mais bon ça reste un truc rare et qui doit pas se faire souvent (on s'amuse pas à bloquer débloquer plein de fois à la suite). Donc oui la première solution parait immensément plus économique et facile à faire.

L'autre en plus d'être plus couteux, c'est plus compliqué à maintenir, puisque ça veut dire qu'il faut penser à ajouter ces exceptions possiblement à plusieurs endroits et rien oublier.

**Comment by brunob** [comment]
Pour la seconde option, @Fil proposait la modification suivante ici https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L209

```php
sql_select("f.id_follow", "spip_me_follow f LEFT JOIN spip_me_block b ON
(b.id_block=f.id_auteur and b.id_auteur=f.id_follow OR
b.id_block=f.id_follow and b.id_auteur=f.id_auteur)",
"id_auteur=$id_auteur_me AND b.id_block IS NULL");
```

**Comment by rastapopougros** [comment]
Oui c'est pour ça que j'avais mis les deux manières quand même. Donc ok allons plutôt pour la deuxième.

**Comment by brunob** [comment]
Doit être réglé par https://github.com/seenthis/seenthis/pull/29, je ferme, n'hésitez pas à le signaler si "on" a oublié des bouts...

**Comment by rastapopougros** [comment]
Super, merci !
