### ISSUE TITLE
Pas de message d'erreur lorsque le mot de passe est incorrect

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/seenthis_squelettes#234]
J'essaie de me connecter à mon compte SeenThis depuis un Firefox, mais je suis sans cesse ramené à l'écran sans connexion. Je veux bien croire que je me trompe de mot de passe (quoique, depuis deux autres machines, ça passe avec ce mot de passe), mais dans ce cas, cela serait sympa d'avoir un message d'erreur genre « nom d'utilisateur ou mot de passe incorrect ».

**Comment by khodr** [comment]
Hello
Depuis le passage a SPIP 3 cela m'arrive tout le temps, je suis obligé de
cliquer sur mot de passe oublié puis remettre le meme mot de passe pour que
ça marche.

George

**Comment by bortzmeyer** [comment]
Alors, j'ai bien regardé, et le message apparait en effet mais pendant une fraction de seconde seulement. Cela le rend inutile.

**Comment by brunob** [comment]
@bortzmeyer non pas chez moi, au rechargement de la page le formulaire de login reste affiché et le message est bien là. Qu'observes-tu exactement de ton côté ?

**Comment by bortzmeyer** [comment]
@brunob Je vois le message et il disparait spontanément au bout d'une seconde.

**Comment by brunob** [comment]
@bortzmeyer de mon côté, que ça soit avec firefox ou chromium, le formulaire de login reste affiché au retour d'erreur. Tu confirmes que chez toi il disparaît après le rechargement de la page ?

**Comment by brunob** [comment]
Pas de nouvelle, bonne nouvelle ? On peut fermer ou le bug est confirmé ?

**Comment by bortzmeyer** [comment]
La bogue est toujours là et je ne peux pas me connecter à SeenThis.

**Comment by bortzmeyer** [comment]
J'ai changé mon mot de passe (en mettant exactement le même) et ça m'a permis de me connecter.
