### ISSUE TITLE
API cassée ?

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/seenthis_squelettes#235]
Ah cool, maintenant, c'est l'API qui ne marche plus ("Error 401: Unknown user")

**Comment by brunob** [comment]
Testé à l'instant, "ça marche chez moi".

**Comment by bortzmeyer** [comment]
Bon, en fait, le message est trompeur, "HTTP Error 401: Unknown user" veut dire que le mot de passe n'est pas correct (je l'avais changé, mais oublié le fichier de configuration).

**Comment by Fil** [comment]
N'est-ce pas une bonne pratique de sécurité de ne donner aucune info sur l'existence ou non du login si le mdp est mauvais ?

**Comment by bortzmeyer** [comment]
Dans ce cas, le message devrait être "Erreur d'authentification, utilisateur inconnu ou mot de passe incorrect", pas juste "Utilisateur inconnu".

**Comment by brunob** [comment]
@bortzmeyer paye ton patch :)

**Comment by brunob** [comment]
Le patch est offert, il n'attend plus que vos retours.
