### ISSUE TITLE
Problème dans la détection des arborescences d'URL

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#242]
On dirait qu'il y a un soucis dans la détection des arborescences d'URL.

Seenthis ne fait pas que des pages avec "tous les seens contenant telle URL", mais aussi normalement à chaque fois il rajoute un site par morceaux de chemin parent "/truc/chemin" et in fine avec le domaine racine.

Or par exemple là pour reporterre.net : https://seenthis.net/sites/960815 le tout premier seen date d'il y a 4 mois !
Alors qu'évidemment il y en a eu des dizaines depuis et rien que cette semaine : https://seenthis.net/recherche?recherche=reporterre

J'ai pas encore regardé pour d'autres domaines mais c'est sûrement pareil. Pourquoi trouve-t-il bien ceux d'il y a 4 mois mais plus ensuite ? un changement à ce moment ?

**Comment by brunob** [comment]
C'est certainement en rapport avec #239 et je l'ai signalé dans #130 sans avoir eu le moindre retour.

**Comment by brunob** [comment]
Je viens de regarder, déjà, dans https://github.com/seenthis/seenthis_squelettes/blob/master/seenthissq_fonctions.php#L40 on récupère 100 urls liés à un site sans préciser `order by` ce qui ne fait pas remonter les derniers référencements cf : 

```sql
MariaDB [stdev]> SELECT id_syndic, url_site, date FROM spip_syndic WHERE id_parent = 960815 limit 0,2 \G
*************************** 1. row ***************************
id_syndic: 1804558
 url_site: https://reporterre.net/La-Zad-de-Bretignolles-sur-Mer-evacuee-en-plein-confinement
     date: 2020-04-09 13:53:50
*************************** 2. row ***************************
id_syndic: 1515163
 url_site: https://reporterre.net/ALT-En-Charente-un-village-fait-le-pari-d-une-gestion-collective-des-terres
     date: 2018-10-18 09:29:33
```

VS

```sql
MariaDB [stdev]> SELECT id_syndic, url_site, date FROM spip_syndic WHERE id_parent = 960815 order by date DESC limit 0,2 \G
*************************** 1. row ***************************
id_syndic: 7282461336007530296
 url_site: https://reporterre.net/L-Autorite-de-regulation-censure-une-pub-pour-un-velo-qui-critique-l-impact-de-la-voiture
     date: 2020-07-02 09:14:36
*************************** 2. row ***************************
id_syndic: 7282461336007528359
 url_site: https://reporterre.net/Un-rapport-pointe-les-effets-toxiques-des-gaz-lacrymogenes
     date: 2020-06-28 11:43:45
```

Je viens d'appliquer le patch suivant en prod et le résultat montre bien les 100 référencements les plus récents cf https://seenthis.net/sites/960815?var_mode=recalcul

```diff
diff --git a/seenthissq_fonctions.php b/seenthissq_fonctions.php
index 95e5fe5..61b3963 100644
--- a/seenthissq_fonctions.php
+++ b/seenthissq_fonctions.php
@@ -37,7 +37,7 @@ function calculer_enfants_syndic($id_syndic, $url_racine = '', $afficher_url = '
 		$ret[] = $doublon;
 	}
 	
-	$query = sql_select("*", "spip_syndic", "id_parent=$id_syndic", /* group by */ '', /* order by*/ '', /* limit */ '0,100');
+	$query = sql_select("*", "spip_syndic", "id_parent=$id_syndic", /* group by */ '', /* order by*/ 'date desc', /* limit */ '0,100');
 	$total = sql_count($query);
 	
 	if ($afficher_url) {
```

À voir si c'est bien ce qu'on souhaite, perso ça me semble cohérent d'afficher ces items par date, mais il ne faut pas oublier qu'on n'en liste que 100 (et ne me demandez pas pourquoi).

**Comment by rastapopougros** [comment]
Ça serait déjà ça les 100 plus récents oui… mais du coup c'est pas du tout intuitif dans l'interface, ce n'est pas ça que l'on comprend. Si je suis sur la page d'un site complet (notamment un domaine entier, en remontant l'arbo), ce qu'on s'attend à voir c'est 100% des seens (+ commentaires) où sont évoqués ce domaine. Ya un problème de perf ?

C'est d'autant plus important qu'il me semble que la recherche libre squize les URL des textes pour chercher (ça les surligne dans le résultat final, mais ça ne l'utilise pas dans la recherche). Autrement dit, si je cherche "reporterre" alors que le mot n'est pas dans le texte normal du seen mais seulement dans des URL, ça ne va pas remonter.

**Comment by brunob** [comment]
Il y a deux choses différentes ici : 

- l'affichage des urls enfants d'un site dans le haut de la page, qui est limité à 100 items depuis https://github.com/seenthis/seenthis_squelettes/commit/b6cfe61ee411e8a9e5ddcbef5360793790017f9f
- l'affichage des seens liés à ces urls, qui lui n'est pas limité à 100 items, exemple https://seenthis.net/sites/1165210

**Comment by rastapopougros** [comment]
aaah pardon oui j'avais mal compris !

Les "morceaux enfants" en haut, c'est normal de limiter, en tout cas si ya pas une pagination, sinon ça peut être énorme non ? Quoique faudrait regarder c'est quoi le nombre de morceaux enfants le plus grand actuellement, et en déduire si c'est vraiment utile de limiter

**Comment by brunob** [comment]
Pour le second point que je listais, cad les messages liés à une url : une piste serait d'ajouter un argument à la fonction `calculer_enfants_syndic()` afin de pouvoir lui passer la limite de la requête sql en paramètre. Ainsi, dans le corps de la page, on pourrait bien boucler sur les messages liés à toutes les occurrences de l'url et pas seulement les 100 dernières en date.

**Comment by brunob** [comment]
J'ai un patch qui semble faire le job, https://seenthis.net/sites/960815 affiche maintenant 1080 messages au lieu de 360. J'envoie ça dans une PR et on attend deux mois pour le merger ou je pousse en prod cash ?

```diff
diff --git a/noisettes/contenu/contenu_site.html b/noisettes/contenu/contenu_site.html
index 0590337..163ee18 100644
--- a/noisettes/contenu/contenu_site.html
+++ b/noisettes/contenu/contenu_site.html
@@ -5,7 +5,7 @@
 ]
 
 <BOUCLE_principale(SYNDIC){id_syndic=#ENV{id}}{tout}>
-	[(#SET{tous_sites,[(#ID_SYNDIC|calculer_enfants_syndic{#URL_SITE})]})]
+	[(#SET{tous_sites,[(#ID_SYNDIC|calculer_enfants_syndic{#URL_SITE,'',#ARRAY,true})]})]
 	#SET{messages, #ARRAY{}}
 	
 	<BOUCLE_tous_liens(ME spip_me_syndic){spip_me_syndic.id_syndic IN #GET{tous_sites}}>
diff --git a/seenthissq_fonctions.php b/seenthissq_fonctions.php
index 61b3963..7193886 100644
--- a/seenthissq_fonctions.php
+++ b/seenthissq_fonctions.php
@@ -27,7 +27,7 @@ function share_tw_url($id_me) {
 	return $me;
 }
 
-function calculer_enfants_syndic($id_syndic, $url_racine = '', $afficher_url = '', $ret = array()) {
+function calculer_enfants_syndic($id_syndic, $url_racine = '', $afficher_url = '', $ret = array(), $nolimit = false) {
 	
 	$ret[] = $id_syndic;
 	
@@ -37,7 +37,7 @@ function calculer_enfants_syndic($id_syndic, $url_racine = '', $afficher_url = '
 		$ret[] = $doublon;
 	}
 	
-	$query = sql_select("*", "spip_syndic", "id_parent=$id_syndic", /* group by */ '', /* order by*/ 'date desc', /* limit */ '0,100');
+	$query = sql_select("*", "spip_syndic", "id_parent=$id_syndic", /* group by */ '', /* order by*/ 'date desc', /* limit */ $nolimit ? '' : '0,100');
 	$total = sql_count($query);
 	
 	if ($afficher_url) {

```

**Comment by rastapopougros** [comment]
magueunifique ! go go
