### ISSUE TITLE
Echapper le caractère &nbsp; dans le flux Twitter

### ISSUE THREAD

**Issue by xelab** [seenthis/seenthis_squelettes#245]
Bonjour,

j'espère être au bon endroit! J'ai voulu essayer l'interfaçage avec Twitter via ifttt mais le problème c'est que mon flux appelé à l'url feed_tw est cassé : 
https://seenthis.net/people/alexcorp/feed_tw
`Erreur d’analyse XML : entité non définie
Emplacement : https://seenthis.net/people/alexcorp/feed_tw
Numéro de ligne 40, Colonne 14 :
		<name>Basta&nbsp;! (@bastamag)</name>
---------------------------^`

Il semble que le caractère HTML `&nbsp;` n'est pas supporté dans les XML, il faut l'échapper de cette façon : `&amp;nbsp;` (ou bien l'écrire : `&#160;`)

Edit : mes posts apparaissent malgré tout dans le fil Twitter donc cela fonctionne quand même.

**Comment by brunob** [comment]
Corrigé, merci pour le signalement :)
