### ISSUE TITLE
Lien JS d'édition cassé, quand on cherche à modifier un contenu qui vient d'être modifié et rechargé en ajax

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#247]
Quand on édite un contenu déjà existant, alors le seen + ses commentaires se rechargent en ajax.

Une fois ce rechargement fini, si on cherche à modifier de nouveau, alors le lien ne recharge pas le bloc avec le form d'édition, mais fait un vrai lien vers l'accueil avec comme ancre l'id de ce qu'on cherchait à modifier. Et c'est insupportable ! :D (ça a toujours fait ça depuis le début)

On est alors obligé de recharger la page dédiée du seen pour de nouveau le modifier.

(Dans tous les cas ces éditions sont un peu bof, avec tout en JS alors que ça devrait plutôt marcher sans JS càd avec des URL permettant d'accéder à l'édition même quand JS marche pas, et que le chargement du form en JS soit de l'amélioration progressive. Bon c'est un autre sujet qui devrait être un autre ticket… :p )

**Comment by rastapopougros** [comment]
Lié à #171 ou même doublon.

Le rechargement ajax provoque deux choses (qui soit sont liées, càd que l'un est la conséquence de l'autre, soit juste arrivent en même temps et faut corriger les deux) : 
1) le href du lien "Modifier" n'est plus le bon, au lieu d'être la page en cours self()#messageyyyyy, c'est uniquement seenthis.net#messageyyyyy
2) le comportement javascript ajax est pété, est ça ne ré-ouvre pas le form en ajax et donc ça suit le href mauvais et ça revient à l'accueil

**Comment by brunob** [comment]
Dans #171 il est précisé que ça se passe depuis sa propre page, donc `people/b_b` par exemple, c'est bien le cas dans ce que tu observes ?

J'ai testé depuis la page d'accueil, après avoir paginé bien sûr, et je ne reproduis pas dans ce cas.

Si c'est bien un doublon de #171, je préfère qu'on ferme ici et qu'on en cause dans le ticket initial.

**Comment by rastapopougros** [comment]
Non c'était depuis n'importe quelle page pour moi (enfin je vais rarement sur l'accueil donc au moins depuis un seen précis ou depuis la liste d'une recherche).

Le HREF ne sert à rien mais il est alors utilisé par le nav si le JS est pété à un moment. Et du coup ça suit en plus un faux HREF qui ramène à l'accueil, au lieu d'un bon lien vers self+#id (ce qui serait un moindre mal, puisque permettrait de recliquer sur Modifier)

**Comment by brunob** [comment]
Ok, je ferme ici puisque ça semble bien un doublon.
