### ISSUE TITLE
API en panne (erreur 500)

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/seenthis_squelettes#249]
Ce matin, on ne peut pas écrire via l'API (on récupère une erreur 500 "Internal Server Error").

Ça marche depuis l'interface Web.

**Comment by brunob** [comment]
Je regarde ça, mais grml impossible de retrouver comment on utilise cette API (j'étais pourtant persuadé d'avoir noté ça quelque part).

**Comment by brunob** [comment]
Testé à l'instant, pas d'erreur... tu confirmes ?

**Comment by bortzmeyer** [comment]
Oui, ça remarche, merci. C'était quoi ?

**Comment by brunob** [comment]
Je ne sais pas j'étais pas présent ce matin et j'ai un peu la flemme de fouiller dans les logs :p
