### ISSUE TITLE
Le système d'embed ne gère pas les playlists Youtube

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#250]
Je ne sais jamais à quel niveau c'est fait, mais en résultat final c'est dans Seenthis alors je fais le ticket là pour l'instant :p

Donc le lecteur à intégrer de Youtube sait parfaitement gérer les playlists, et dans ce cas, autour du bouton "play", ya des boutons précédent et suivant. Exemple : 
https://www.fip.fr/jazz/kamasi-washington-terrace-martin-9th-wonder-et-robert-glasper-sortent-dinner-party-18208

Mais dans Seenthis, il ne détecte jamais la playlist, et il ne permet donc de lire que le seul morceau fourni, obligé d'aller chez Youtube pour avoir tout (et même pour le savoir si on n'a pas prévenu que c'était une playlist).
https://seenthis.net/messages/867846

**Comment by brunob** [comment]
> Je ne sais jamais à quel niveau c'est fait, mais en résultat final c'est dans Seenthis alors je fais le ticket là pour l'instant :p

Ça se passe par là https://git.spip.net/spip-contrib-extensions/seenthis_autoembed :)

**Comment by brunob** [comment]
Corrigé cf https://git.spip.net/spip-contrib-extensions/seenthis_autoembed/issues/1 :)
