### ISSUE TITLE
Écriture inclusive

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#256]
Remplacer @auteurs par @personnes dans le header, puis pour tous les autres termes comme "abonnés" etc.

Ref https://seenthis.net/messages/896860

**Comment by cy-altern** [comment]
m'étant bien fait "balancer" par b_b, je n'avais plus qu'a aller au bout de la tentative... 
Alors : https://github.com/seenthis/seenthis_squelettes/pull/257
