### ISSUE TITLE
Mon mot de passe sur la machine

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/seenthis_squelettes#261]
Mon mot de passe sur la machine SeenThis est refusé. Je ne l'ai pas utilisé depuis longtemps, je suppose donc que le compte a été supprimé/verrouillé. (C'était pour chercher une solution à #260 )

**Comment by brunob** [comment]
concerne plutôt le repo https://github.com/seenthis/hebergement/ mais pour confirmation, je ne vois aucune trace de compte à ton nom sur la machine actuelle.
