### ISSUE TITLE
Utiliser l'API autoriser

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#262]
Comme je le disais sur IRC : 

```
< b_b‎ >  faut que je permette aux admins d'un seenthis de modifier les messages
< b_b‎ >  et c'est la misère
< b_b‎ >  aucune des fonctions qui gère l'édition/suppression n'est en _dist
< b_b‎ >  donc, deux options : un define qui permet de faire ça
< b_b‎ >  ou intégrer des vrais autorisations
< b_b‎ >  en plus une des fonctions est dans seenthis et l'autre dans le squelette
```

Il serait plus adapté d'utiliser l'API autoriser pour permettre aux différentes instances de seenthis de surcharger ça proprement :)

**Comment by rastapopougros** [comment]
+1 c'est le plus propre, chaque fonction de modif / action, devrait utiliser autoriser()

**Comment by brunob** [comment]
Voilà, c'est en place pour tester la modification et la suppression d'un message, une bonne base qu'on peut déjà merger *après* vos relectures éclairées :)

**Comment by brunob** [comment]
@seenthis/commiters j'attends vos +1 pour merger :) 

(merci @rastapopougros pour le premier envoyé)

**Comment by cy-altern** [comment]
ça me semble bien comme ça : utiliser une autorisation c'est ce qui laisse le plus de possibilité si on doit faire évoluer plus tard

**Comment by brunob** [comment]
Intégré, on ferme ici, on aura tout le loisir d'utiliser ces autorisations partout où ça sera nécessaire dans le code au fil de nos découvertes :)

**Comment by brunob** [comment]
Un potentiel bug sur la suppression de message signalé ici https://seenthis.net/messages/915286

**Comment by brunob** [comment]
Corrigé par https://github.com/seenthis/seenthis/commit/327a9a22945deb1bdad01c0aaafbba269314110e
