### ISSUE TITLE
Autoriser l'accès à l'espace privé uniquement pour les admins

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_squelettes#267]
Je viens de remarquer que les rédacteurs ont accès à l'espace privé, rien de bien méchant car tous les comptes créés depuis le public sont en mode 6forum, mais je pense qu'on devrait tout de même interdire le privé aux rédacteurs avec ça dans le fichier d'options de seenthis :

```php
// autoriser le prive uniquement pour les admins
function autoriser_ecrire($faire, $type, $id, $qui, $opt) {
	return $qui['statut'] == '0minirezo';
}
```

Sans contre avis de @seenthis/commiters j'envoie ça dans la semaine :)

**Comment by cy-altern** [comment]
d'autant +1 que le SPIP de Seenthis n'a pas les *merveilleuses* améliorations de l'espace privé de la 3.3-dev ;-)
