### ISSUE TITLE
Image qui ne se charge pas

### ISSUE THREAD

**Issue by biggrizzly** [seenthis/seenthis_squelettes#274]
Jusqu'alors, j'utilisais mon outil de partage de fichiers pour partager des images sur SeenThis, plutôt que d'envoyer le lien Twitter... Et je constate aujourd'hui qu'il semble que SeenThis n'est plus en mesure de charger l'image. 

Ça se passe là : 
https://seenthis.net/messages/938529#message938552

L'image en question : 
https://www.partagerfichier.fr/download/2021-12-03-07-58-00_ffn2eg9xoakgcc2.jpeg

Je soupçonne que ce soit en lien avec l'issue précédente #214

**Comment by brunob** [comment]
Je viens de vérifier rapidement avec `var_dump(cache_exists('https://www.partagerfichier.fr/download/2021-12-03-07-58-00_ffn2eg9xoakgcc2.jpeg'))` et l'image en question ne semble pas être "en lock".

Je vais poser quelques logs dans `copie_locale_safe()` pour voir en détail...

**Comment by brunob** [comment]
Je viens de vérifier en local en ajoutant l'image directement depuis l'espace privé et le problème est le même, après copie locale du fichier on se retrouve avec `IMG/bin/2021-12-03-0b863.bin`, idem en prod.

Ça ressemble à un problème de détection du type de fichier et je me demande si ça ne vient pas de son extension jpeg et non jpg, ce qui me rappelle ces tickets récents sur SPIP https://git.spip.net/spip/medias/issues/4850 & https://git.spip.net/spip/spip/issues/4958

En local mon seenthis fonctionne sous PHP 7.2.34, en prod on est en PHP Version 7.1.30, je vais voir si le bug se reproduit avec un PHP 7.4.

**Comment by biggrizzly** [comment]
Exactement ! 
La même image en jpg...
https://www.partagerfichier.fr/download/2021-12-03-10-02-26_ffn2eg9xoakgcc2.jpg

**Comment by brunob** [comment]
Ticket ouvert sur SPIP https://git.spip.net/spip/spip/issues/4960

**Comment by brunob** [comment]
FTR, c'est réglé dans SPIP maintenant, et dispo dans la branche 3.2 mais avant d'en profiter il faut qu'on up seenthis en 3.2 après avoir réglé #275, on ferme :)
