### ISSUE TITLE
Notification de la part d'utilisateurs bloqués

### ISSUE THREAD

**Issue by biggrizzly** [seenthis/seenthis_squelettes#282]
Apparemment, on peut recevoir des notifications pour des commentaires créés par des personnes bloquées. 

`Je bloque @toto. J'étoile ou j'interviens sur un fil créé par @popeye. @toto crée un commentaire dans le fil. Je reçois une notification de la part de @toto.`

Voici un fil où ce phénomène semble avoir eu lieu :
https://seenthis.net/messages/942574#message942951

**Comment by brunob** [comment]
J'ai quoté ta phrase avec les @ sans quoi ces utilisateurs github ne vont pas comprendre pourquoi tu les ping :p

**Comment by biggrizzly** [comment]
Bien vu :-)))

**Comment by brunob** [comment]
Donc, ça se passe dans `notifier_me()` https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L166

On peut lire que la fonction retire des destinataires de la notification :
- les destinataires cités dans le message sauf s'ils bloquent l'auteur
- les comptes bloqués par l'auteur du post à notifier

Ce qui met en évidence qu'il manque bien un filtre afin de ne pas notifier les messages postés par une personne bloquée vers les compte qui la bloquent.

**Comment by brunob** [comment]
Je suis toujours un peu concon devant ce genre de cas A/B VS B/A mais je pense que le patch suivant ferait l'affaire :

```diff
diff --git a/inc/seenthis_notifier.php b/inc/seenthis_notifier.php
index 1fa64d9..40a4e5d 100644
--- a/inc/seenthis_notifier.php
+++ b/inc/seenthis_notifier.php
@@ -281,6 +281,11 @@ function notifier_me($id_me, $id_parent) {
 	while ($t = sql_fetch($s)) {
 		$remove[] = $t['id_auteur'];
 	}
+	// ni vers les comptes qui bloquent
+	$u = sql_query($q = 'SELECT id_auteur FROM spip_me_block WHERE id_block IN (' . sql_quote($id_auteur).','.sql_quote($id_auteur_me).')');
+	while ($v = sql_fetch($u)) {
+		$remove[] = $v['id_auteur'];
+	}
 
 	foreach ($remove as $id_r) {
 		foreach ($id_dest as $k => $id) {
```

Vous en pensez quoi @Fil & @rastapopougros ?

**Comment by rastapopougros** [comment]
Je sais pas, tu parles de quoi pour A/B vs B/A ? J'ai pas tout compris

**Comment by brunob** [comment]
Oubliez ma remarque et mon patch, je viens de tester en local ça n'est pas bon, je m'y recolle.

**Comment by brunob** [comment]
Voilà, micro PR à valider, testé en local, ça fonctionne.

**Comment by brunob** [comment]
Il semblerait que ça n'est pas au point, à tester/vérifier https://seenthis.net/messages/943343#message946308

**Comment by brunob** [comment]
Ha ben vi... ça fonctionnera mieux comme ça https://github.com/seenthis/seenthis/commit/ae81296f788084e98dcae0d60ab8db059c02e7fc
