### ISSUE TITLE
Les images de twitter ne s'ouvrent jamais en grand, alors que l'URL est bonne

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#285]
Je ne sais pas si ça le fait pour d'autre chose que twitter. Mais depuis le tout début, à chaque fois que quelqu'un met une image de twitter, ça génère bien un aperçu direct (donc SPIP arrive bien à récupérer l'image depuis l'extérieur), mais quand on clique dessus pour ouvrir en grand : ça fait une erreur. Alors que si on fait ouvrir dans un nouvel onglet : on a bien l'image originale en grand.

Exemple récent : https://seenthis.net/messages/953098

**Comment by Cerdic** [comment]
J'ai vu la semaine dernière en corrigeant oEmbed que Twitter fait visiblement maintenant une verif de referer sur son serveur d'image, et on ne peut plus les afficher depuis un autre site.

SPIP peut télécharger l'image et faire une `copie_locale()`, on peut l'afficher dans un nouvel onglet, mais pas dans une popin depuis un autre site

**Comment by brunob** [comment]
Ha oui, je vois ça dans les outils de dev, étonnant cette valeur "tracking" pour le transfert de l'image...

![image](https://user-images.githubusercontent.com/418064/158675170-9a7ce1ef-066d-4cd9-ba4f-8f9381ed645c.png)

**Comment by brunob** [comment]
@Cerdic merci pour l'info, je pense qu'on ne pourra pas se permettre de faire des copies locales de toutes les images en provenance de twitter sur seenthis, les gens vont devoir en faire le deuil si on ne trouve pas une autre parade :\

**Comment by Cerdic** [comment]
Ça marcherait peut être de l’afficher dans une iframe (c’est vraiment une rustine)

**Comment by brunob** [comment]
Je viens de tester sous chromium en navigation privée, les images s'affichent bien. Idem sous firefox en mode normal, mais ça ne passe pas en navigation privée avec ce dernier. Je me demande si ça ne viendrait pas d'une liste de blocage pour protection de la vie privée cf https://github.com/mozilla/blok/issues/187 & https://bugzilla.mozilla.org/show_bug.cgi?id=1458915

**Comment by rastapopougros** [comment]
Ah moi je navigue pas sur seenthis en nav privée, donc c'est bien en nav normale que ça ne marche pas

**Comment by brunob** [comment]
Oui, mais en nav normale tu peux avoir des réglages différents dans les options de vie privée (réglages qui sont tous à bloc en mode navigation privée). Est-ce que tu confirmes ce que je montrais dans la capture d'écran des outils de dev plus haut ? Si oui, c'est bien un problème local (options du navigateur) et à part passer par de la copie locale (ce qui ne me semble pas envisageable) on n'y pourra rien je pense.

**Comment by rastapopougros** [comment]
Oui j'ai deux lignes Tracking qui s'ajoutent aussi à chaque clic sur une image de twitter.

**Comment by brunob** [comment]
C'est bien ça donc, perso dans les préférences de FF au niveau vie privée je suis en mode "Standard", alors que le mode "Stricte" bloque plus de chose, notamment la partie en surbrillance dans la capture ci-dessous "Contenu utilisé pour le pistage dans toutes les fenêtres".

![image](https://user-images.githubusercontent.com/418064/159176267-09280cd8-ddf5-4a3d-9732-ba47050f1e86.png)

En mode standard, ça ne bloque qu'en navigation privée, en mode strict, ça bloque tout le temps. Si tu es en mode stricte, essaye en mode standard, ça devrait confirmer la piste. Aparté, le mode stricte affiche bien l'avertissement suivant "Protection renforcée, mais certains sites ou contenus peuvent ne pas fonctionner correctement.".

**Comment by rastapopougros** [comment]
Ni l'un ni l'autre, je suis en "personnalisé" :p mais avec bien pour toutes les fenêtres pour cette option oui

Plus pointu, je l'ai plutôt désactivé *uniquement pour seenthis*, dans le menu "Protection" avec l'icone bouclier à gauche de la barre d'adresse, ya un bouton glissière directement là pour chaque site. Et ça remarche ! :)

**Comment by brunob** [comment]
On peut donc considérer que c'est un problème de configuration de navigateur et fermer le ticket ?

**Comment by rastapopougros** [comment]
Allez un de moins dans cette longue liste
