### ISSUE TITLE
La touche Entrée seule poste le message au lieu d'aller à la ligne, quand on vient d'alterner entre onglets au clavier

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#287]
Je ne sais pas si ça le fait que avec le raccourci "Ctrl-tab" qui permet d'alterner entre onglet, ou si c'est spécifiquement la touche "Ctrl" ou autre.

Mais en plein milieu de la rédaction d'un message pas fini, si on est parti ailleurs relire ou copier des choses avec le clavier, et qu'on revient sur la page où on rédigeait, alors la touche Entrée poste directement le message ! (alors qu'on appuyait plus sur rien d'autre)

Et c'est super chiant vu que c'était pas fini, et que du coup ça envoie une notif aux abonnés etc avec un message coupé en plein milieu (sauf si on se dépêche de le supprimer et le refaire à zéro).

Ça m'a toujours fait ça depuis le tout début.

**Comment by brunob** [comment]
Ça doit venir de là https://github.com/seenthis/seenthis_squelettes/blob/c80eee4a079840ae2cd5fcb485f84c956a355596/javascript/seenthis/seenthis.js#L277

Amha faut pas s'emmerder et virer ces trucs, pas besoin de tenter de gérer des raccourcis claviers, il y a des "boutons" pour ça. Si jamais "on" souhaite garder ça, il faut s’appuyer sur une lib robuste afin de bien détection les raccourcis sans erreur de ce type.

**Comment by martinarnaud** [comment]
Alors moi j'y tiens, le maj+entrée pour poster, et le maj+tab pour citer, je trouve ça ultra-pratique, je fait tout avec ça. 

Par contre, je n'utilise jamais la version avec ctrl, je ne me souviens plus du tout pourquoi il y a les deux, alors que dans l'interface c'est juste la version maj+entrée qui est indiquée. Est-ce que virer la version ctrl serait problématique (vu que non documentée), et est-ce que ça résoudrait le souci de Rasta? (Est-ce que ce serait une histoire de compatibilité avec Windows ou un autre système?)

**Comment by rastapopougros** [comment]
Après c'est quand même pratique et connu comme fonctionnalité.

Là en lisant un peu le code, j'imagine bien un truc de ce genre : 
- le test se fait sur keyDOWN et ça met une GLOBALE à isCtrl ou isShift
- or si je change d'onglet avec Ctrl+Tab alors le keyUP… se passe alors qu'on s'est déjà barré sur l'autre onglet !
- donc on n'a jamais le https://github.com/seenthis/seenthis_squelettes/blob/c80eee4a079840ae2cd5fcb485f84c956a355596/javascript/seenthis/seenthis.js#L295
- du coup quand on revient dans l'autre sens, globalement c'est toujours à "true", et dès qu'on veut passer à la ligne avec Entrée, ça poste

**Comment by rastapopougros** [comment]
Ah bé on a posté pile exactement en même temps @martinarnaud  :)  

Il me semble que oui : supprimer juste la version Ctrl résoudrait le problème, car c'est avec Ctrl qu'on change d'onglets dans le navigateur (Ctrl-Tab ou Ctrl-<numero> ou Ctrl-PageUp/Down).

Et moi aussi, vu que c'est comme ça que c'est documenté, c'est avec Maj+Entrée que je poste quand j'ai fini, et jamais avec Ctrl.

**Comment by brunob** [comment]
Le "sondage" lancé par @martinarnaud a parlé, toujours pas de PR à ce sujet ?

**Comment by brunob** [comment]
Et hop, PR testé en local, à relier et valider.
