### ISSUE TITLE
option pour ne pas recevoir de notification sur les réponses aux messages qu'on a partagés

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#37]
@lazuly says:
> Par exemple, qu'un billet que je partage apparaisse dans ma home page comme si c'était le mien, ça me choque pas, de la même façon qu'un RT d'un tweet d'un autre apparaît dans ma TL Twitter, normal, c'est une expression de ma part.

> Par contre, les dix commentaires sur l'article du Monde que j'ai partagé (mais pas du tout commenté) ne méritent pas d'alertes. 

> Si je poste personnellement un truc, je veux une alerte ("t'as dit une connerie, blabla"), mais si j'ai juste trouvé intéressant un article, je ne veux pas recevoir une alerte à chaque considération sur le sujet (alerte genre "oui, n'oublions jamais que les Japonais s'immiscent parfois dans la zone de pêche des Chinois").

**Comment by archiloque** [comment]
Ça signifie que pour chaque article il faut une case à cocher indiquant si je veux être notifié des commentaires sur cet article en particulier ?

**Comment by Fil** [comment]
Ce serait assez horrible en termes d'UI. Je dirais plutôt, dans les
préférences de notifications, ajouter un choix distinguant mes messages de
ceux que j'ai partagés.
>
>
