### ISSUE TITLE
Images sur le texte dans les flux Atom

### ISSUE THREAD

**Issue by rastapopougros** [seenthis/seenthis_squelettes#41]
Depuis quelques temps (1 ou 2 semaines ?) les URLs des images passent par-dessus le texte classique dans les flux. En tout cas dans mon lecteur, c'est-à-dire Thunderbird.

![atom-seenthis](https://cloud.githubusercontent.com/assets/2677871/5092400/30c19e7a-6f4f-11e4-840e-77e8726f026a.png)

Avant ça ne le faisait pas, ces URLs étaient avant ou après, sur toutes la longueur, mais pas en "flottant" comme ça.

**Comment by brunob** [comment]
@rastapopougros le problème est-il toujours d'actualité ?

**Comment by rastapopougros** [comment]
Nope ça a l'air résolu. Par contre il reste le problème du lien de l'image dans les flux, qui lui est toujours avec une énorme hauteur (et du coup va sur le texte), mais faudrait un ticket dédié. Je crois que j'avais fait un seen dessus au moins.

**Comment by brunob** [comment]
Ok on peut fermer alors, merci pour le retour. Perso, je viens de tester la syndication du flux https://seenthis.net/tag/b%C3%A9po/feed dans le module news de nextcloud et je ne reproduis pas le bug du lien de l'image que tu mentionnes.
