### ISSUE TITLE
Cliquer sur l'identifiant pour ouvrir une réponse avec @ pré-rempli

### ISSUE THREAD

**Issue by lddfr** [seenthis/seenthis_squelettes#42]
Amélioration qui me paraîtrait très appréciable : l'identifiant qui se trouve en bas de chaque message, avec le vrai identifiant unique d'utilisateur, pourrait rester avec le même lien (aller vers la page de l'utilisateur) MAIS en javascript, cela pourrait faire défiler en bas + ouvrir la boite de réponse + pré-remplir le champ avec `@identifiant`.

Cela permettrait, pour celleux qui ont JS, de ne pas avoir à se souvenir ou à retaper ou à copier-coller les identifiants compliqués de certain⋅e⋅s (et qui n'ont d'ailleurs parfois aucun rapport avec le nom affiché).

Quand on a pas JS, ou quand on cliquerait avec le bouton du milieu, ça continuerait d'avoir le même comportement qu'avant.

**Comment by goumii** [comment]
Implémenté dans un script greasemonkey (c'est pas forcément optimisé...)

http://seenthis.net/messages/211659
Le script : http://pastebin.com/VNXv2yQv

**Comment by Fil** [comment]
je pense que la solution implémentée avec l'autocomplétion suffit à notre bonheur ?  je ferme, à rouvrir si vous voulez le coder quand même
