### ISSUE TITLE
Compatibilité `$prefixe`

### ISSUE THREAD

**Issue by archiloque** [seenthis/seenthis_squelettes#43]
Migrer seenthis_options.php vers une API SQL portable - Pour permettre notamment d'utiliser un autre prefix que `spip` pour les tables

**Comment by Fil** [comment]
il y a aussi des boucles `(spip_me_tags)`

**Comment by brunob** [comment]
Hop, à propos des boucles spip_me_tags, que ce soit en 2.1 ou 3.0 j'obtiens l'erreur suivante sur la page d'un tag : 
en 2.1
![21](https://cloud.githubusercontent.com/assets/418064/14403280/7c218776-fe51-11e5-835d-fb486dd040b4.png)
en 3.0
![30](https://cloud.githubusercontent.com/assets/418064/14403281/7e91a298-fe51-11e5-817f-3305d304ba3d.png)

Problème, la table spip_me_tags n'est pas déclarée dans tables interface ou surnoms, du coup pas moyen de boucluer sur ME_TAGS.

**Comment by brunob** [comment]
En fait il manque juste un `$interface['table_des_tables']['me_tags']='me_tags';` dans `seenthis_declarer_tables_interfaces()` pour pouvoir boucler sur `ME_TAGS` directement.
