### ISSUE TITLE
sur la page /people/auteur afficher les derniers commentaires de l'auteur, en marge

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#51]
cf. http://seenthis.net/messages/318682

**Comment by brunob** [comment]
On afficherait ça à quel position du coup ? Si la liste est en bas après les tags, ça ne rend pas le truc très accessible, perso je pencherais pour afficher cette liste (de 10 commentaires ?) en premier, avant le bloc qui liste les abonnements de l'auteur.

**Comment by rastapopougros** [comment]
Ça reste à quel point dans le cache ? C'est mis à jour selon à quelle occasion ?
