### ISSUE TITLE
Affichage des dates à moderniser

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_squelettes#60]
un coup de profiler js est assez éloquent…
par ailleurs ce serait sympa qu'on puisse voir en survol la vraie date

**Comment by Fil** [comment]
@archiloque si tu t'ennuies :)

**Comment by archiloque** [comment]
j'ai des trucs à écrire et je regarde ça ensuite

**Comment by martinarnaud** [comment]
Puisqu’on parle de cet endroit: je serais partisan de virer la mention «modifié il y a…». Dans la pratique, je trouve que ça ne sert à rien:
- la plupart des mentions, au final, sont du genre «il y a 2 jours (modifié il y a 2 jours)»
- surtout: comme ça compte évidemment les corrections de fautes de conjugaison aussi bien que les modifications de fond, on n’est pas plus avancés. 

Arnaud

**Comment by Fil** [comment]
Ça pourrait rester si les valeurs sont différentes. Sinon en effet c'est
ridicule

Pour les dates on pourrait juste écrire "à l'instant"/"just now" la
première minute

On Tuesday, January 13, 2015, martinarnaud <notifications@github.com> wrote:

>
>
> Puisqu'on parle de cet endroit: je serais partisan de virer la mention
> <<modifié il y a...>>. Dans la pratique, je trouve que ça ne sert à rien:
> - la plupart des mentions, au final, sont du genre <<il y a 2 jours
> (modifié il y a 2 jours)>>
> - surtout: comme ça compte évidemment les corrections de fautes de
> conjugaison aussi bien que les modifications de fond, on n'est pas plus
> avancés.
>
> Arnaud
>
>
> > Le 13 janv. 2015 à 18:51, Fil <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
> >
> > un coup de profiler js est assez éloquent...
> > par ailleurs ce serait sympa qu'on puisse voir en survol la vraie date
> >
> > --
> > Reply to this email directly or view it on GitHub <
> https://github.com/seenthis/seenthis_squelettes/issues/60>.
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/seenthis/seenthis_squelettes/issues/60#issuecomment-69802144>
> .
>


-- 
-- Fil

**Comment by archiloque** [comment]
Mon dieu ce code

**Comment by archiloque** [comment]
J'ai amélioré le code et désactivé le rafraichissement toutes les secondes quand la page n'est pas affichée

**Comment by Fil** [comment]
optimisations par @archiloque 
http://zone.spip.org/trac/spip-zone/changeset/87138 et http://zone.spip.org/trac/spip-zone/changeset/87139
